
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2012 All rights reserved. 
//=====================================================================

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Globalization;

using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.Platform.Core.ORMapping;
using Siemens.Simatic.Platform.Common;
using Siemens.Simatic.Platform.Common.ExceptionHandling;
using Siemens.Simatic.Platform.Data;
using Siemens.Simatic.Platform.Data.DataAccess;

using Siemens.Simatic.Util.Common;
using Siemens.Simatic.Util.Common.Persistence;

namespace Siemens.Simatic.Util.DataAccess
{
    [DefaultImplementationAttreibute(typeof(DefaultImpl.Plat_util_CodeDetailDAO))]
    public interface IPlat_util_CodeDetailDAO : IDataAccessor<Plat_util_CodeDetail>
    {
    }
}

namespace Siemens.Simatic.Util.DataAccess.DefaultImpl
{
    /// Title: Plat_util_CodeDetailDAO
    /// Copyright: Siemens
    /// Version: 1.0  
    public partial class Plat_util_CodeDetailDAO : IPlat_util_CodeDetailDAO
    {

        #region SQl
        #region SqlInsert
        private const string SqlInsert = @"INSERT INTO dbo.Plat_util_CodeDetail (
                                                [CodeDetailGuid],
                                                [CodeBaseCode],
                                                [CodeDetailCode],
                                                [CodeDetailName],
                                                [CodeDetailDesc],
                                                [CodeDetailValue],
                                                [MySequence],
                                                [IsDefault],
                                                [IsDisplay],
                                                [IsActive]
                                                ) VALUES ( 
                                                @CodeDetailGuid,
                                                @CodeBaseCode,
                                                @CodeDetailCode,
                                                @CodeDetailName,
                                                @CodeDetailDesc,
                                                @CodeDetailValue,
                                                @MySequence,
                                                @IsDefault,
                                                @IsDisplay,
                                                @IsActive
                                            )";
        #endregion

        #region SqlDelete
        private const string SqlDelete = @"DELETE FROM dbo.Plat_util_CodeDetail 
                                           WHERE 1 = 1 
                                           AND CodeDetailGuid = @CodeDetailGuid";
        #endregion

        #region SqlUpdateAll
        private const string SqlUpdate = @"UPDATE dbo.Plat_util_CodeDetail SET
                                            [CodeBaseCode] = @CodeBaseCode,
                                            [CodeDetailCode] = @CodeDetailCode,
                                            [CodeDetailName] = @CodeDetailName,
                                            [CodeDetailDesc] = @CodeDetailDesc,
                                            [CodeDetailValue] = @CodeDetailValue,
                                            [MySequence] = @MySequence,
                                            [IsDefault] = @IsDefault,
                                            [IsDisplay] = @IsDisplay,
                                            [IsActive] = @IsActive
                                            WHERE 1 = 1
                                            AND [CodeDetailGuid] = @CodeDetailGuid";
        #endregion

        #region SqlGet
        private const string SqlGet = @"SELECT
                                            [CodeDetailGuid],
                                            [CodeBaseCode],
                                            [CodeDetailCode],
                                            [CodeDetailName],
                                            [CodeDetailDesc],
                                            [CodeDetailValue],
                                            [MySequence],
                                            [IsDefault],
                                            [IsDisplay],
                                            [IsActive]
                                        FROM dbo.Plat_util_CodeDetail
                                        WHERE 1 = 1 
                                        AND [CodeDetailGuid] = @CodeDetailGuid";
        #endregion

        #region SqlCount
        private const string SqlCount = @"SELECT COUNT(*) 
                                  FROM dbo.Plat_util_CodeDetail 
                                  WHERE ( 1 = 1 {0} ) 
                                          ";
        #endregion SqlCount

        #region SqlSelectAll
        private const string SqlSelectAll = @"SELECT
                                                    [CodeDetailGuid],
                                                    [CodeBaseCode],
                                                    [CodeDetailCode],
                                                    [CodeDetailName],
                                                    [CodeDetailDesc],
                                                    [CodeDetailValue],
                                                    [MySequence],
                                                    [IsDefault],
                                                    [IsDisplay],
                                                    [IsActive]
                                                FROM dbo.Plat_util_CodeDetail 
                                                WHERE (1 = 1 {0} ) {1}
                                        ";
        #endregion SqlSelectAll

        #region SqlSelect
        private const string SqlSelect = @"SELECT TOP {0} 
                                                [CodeDetailGuid],
                                                [CodeBaseCode],
                                                [CodeDetailCode],
                                                [CodeDetailName],
                                                [CodeDetailDesc],
                                                [CodeDetailValue],
                                                [MySequence],
                                                [IsDefault],
                                                [IsDisplay],
                                                [IsActive]
                                           FROM dbo.Plat_util_CodeDetail 
                                           WHERE ( 1 = 1 {1} 
                                           AND CodeDetailGuid 
                                           NOT IN 
                                           (SELECT TOP {2} CodeDetailGuid 
                                           FROM dbo.Plat_util_CodeDetail 
                                           WHERE (1 = 1 {3}) 
                                           {4} ) ) {5} 
                                           ";
        #endregion SqlSelect
        #endregion SQL


        #region IDataAccessor members

        #region Insert
        /// <summary>
        /// Insert 
        /// </summary>  
        public Plat_util_CodeDetail Insert(Plat_util_CodeDetail entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            PersistentPlat_util_CodeDetail Plat_util_CodeDetailEntity = entity as PersistentPlat_util_CodeDetail;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlInsert);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, Plat_util_CodeDetailEntity.CodeDetailGuid);
                db.AddInParameter(dbCommand, "@CodeBaseCode", DbType.String, Plat_util_CodeDetailEntity.CodeBaseCode);
                db.AddInParameter(dbCommand, "@CodeDetailCode", DbType.String, Plat_util_CodeDetailEntity.CodeDetailCode);
                db.AddInParameter(dbCommand, "@CodeDetailName", DbType.String, Plat_util_CodeDetailEntity.CodeDetailName);
                db.AddInParameter(dbCommand, "@CodeDetailDesc", DbType.String, Plat_util_CodeDetailEntity.CodeDetailDesc);
                db.AddInParameter(dbCommand, "@CodeDetailValue", DbType.String, Plat_util_CodeDetailEntity.CodeDetailValue);
                db.AddInParameter(dbCommand, "@MySequence", DbType.Int32, Plat_util_CodeDetailEntity.MySequence);
                db.AddInParameter(dbCommand, "@IsDefault", DbType.Boolean, Plat_util_CodeDetailEntity.IsDefault);
                db.AddInParameter(dbCommand, "@IsDisplay", DbType.Boolean, Plat_util_CodeDetailEntity.IsDisplay);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, Plat_util_CodeDetailEntity.IsActive);

                int result = db.ExecuteNonQuery(dbCommand);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return Plat_util_CodeDetailEntity as Plat_util_CodeDetail;
        }

        /// <summary>
        /// Insert with transaction
        /// </summary>  
        public Plat_util_CodeDetail Insert(Plat_util_CodeDetail entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");
            PersistentPlat_util_CodeDetail Plat_util_CodeDetailEntity = entity as PersistentPlat_util_CodeDetail;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlInsert);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, Plat_util_CodeDetailEntity.CodeDetailGuid);
                db.AddInParameter(dbCommand, "@CodeBaseCode", DbType.String, Plat_util_CodeDetailEntity.CodeBaseCode);
                db.AddInParameter(dbCommand, "@CodeDetailCode", DbType.String, Plat_util_CodeDetailEntity.CodeDetailCode);
                db.AddInParameter(dbCommand, "@CodeDetailName", DbType.String, Plat_util_CodeDetailEntity.CodeDetailName);
                db.AddInParameter(dbCommand, "@CodeDetailDesc", DbType.String, Plat_util_CodeDetailEntity.CodeDetailDesc);
                db.AddInParameter(dbCommand, "@CodeDetailValue", DbType.String, Plat_util_CodeDetailEntity.CodeDetailValue);
                db.AddInParameter(dbCommand, "@MySequence", DbType.Int32, Plat_util_CodeDetailEntity.MySequence);
                db.AddInParameter(dbCommand, "@IsDefault", DbType.Boolean, Plat_util_CodeDetailEntity.IsDefault);
                db.AddInParameter(dbCommand, "@IsDisplay", DbType.Boolean, Plat_util_CodeDetailEntity.IsDisplay);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, Plat_util_CodeDetailEntity.IsActive);

                int result = db.ExecuteNonQuery(dbCommand, transaction);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return Plat_util_CodeDetailEntity as Plat_util_CodeDetail;
        }

        #endregion Insert

        #region Delete
        /// <summary>
        /// Delete 
        /// </summary>  
        public void Delete(object entityId)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlDelete);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, entityId);
                int result = db.ExecuteNonQuery(dbCommand);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }


        /// <summary>
        /// Delete with transaction
        /// </summary>  
        public void Delete(object entityId, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlDelete);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, entityId);
                int result = db.ExecuteNonQuery(dbCommand, transaction);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        #endregion Delete

        #region Get
        /// <summary>
        /// Get
        /// </summary>
        public Plat_util_CodeDetail Get(object entityId)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");

            Plat_util_CodeDetail Plat_util_CodeDetailEntity = null;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlGet);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, entityId);
                using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                {
                    if (dataReader.Read())
                    {
                        Plat_util_CodeDetailEntity = ReadEntity(dataReader);
                    }
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return Plat_util_CodeDetailEntity;
        }


        /// <summary>
        /// Get with transaction
        /// </summary>
        public Plat_util_CodeDetail Get(object entityId, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            Plat_util_CodeDetail Plat_util_CodeDetailEntity = null;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlGet);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, entityId);
                using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                {
                    if (dataReader.Read())
                    {
                        Plat_util_CodeDetailEntity = ReadEntity(dataReader);
                    }
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return Plat_util_CodeDetailEntity;
        }

        #endregion Get

        #region Update

        /// <summary>
        /// Update
        /// </summary>

        public void Update(Plat_util_CodeDetail entity)
        {
            Update(entity, true);
        }

        public void Update(Plat_util_CodeDetail entity, bool updateAll)
        {
            if (!updateAll)
            {
                UpdateSome(entity);
            }
            else
            {
                UpdateAll(entity);
            }
        }

        private void UpdateAll(Plat_util_CodeDetail entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");

            PersistentPlat_util_CodeDetail Plat_util_CodeDetailEntity = entity as PersistentPlat_util_CodeDetail;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlUpdate);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, Plat_util_CodeDetailEntity.CodeDetailGuid);
                db.AddInParameter(dbCommand, "@CodeBaseCode", DbType.String, Plat_util_CodeDetailEntity.CodeBaseCode);
                db.AddInParameter(dbCommand, "@CodeDetailCode", DbType.String, Plat_util_CodeDetailEntity.CodeDetailCode);
                db.AddInParameter(dbCommand, "@CodeDetailName", DbType.String, Plat_util_CodeDetailEntity.CodeDetailName);
                db.AddInParameter(dbCommand, "@CodeDetailDesc", DbType.String, Plat_util_CodeDetailEntity.CodeDetailDesc);
                db.AddInParameter(dbCommand, "@CodeDetailValue", DbType.String, Plat_util_CodeDetailEntity.CodeDetailValue);
                db.AddInParameter(dbCommand, "@MySequence", DbType.Int32, Plat_util_CodeDetailEntity.MySequence);
                db.AddInParameter(dbCommand, "@IsDefault", DbType.Boolean, Plat_util_CodeDetailEntity.IsDefault);
                db.AddInParameter(dbCommand, "@IsDisplay", DbType.Boolean, Plat_util_CodeDetailEntity.IsDisplay);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, Plat_util_CodeDetailEntity.IsActive);
                int result = db.ExecuteNonQuery(dbCommand);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        private void UpdateSome(Plat_util_CodeDetail entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");

            PersistentPlat_util_CodeDetail Plat_util_CodeDetailEntity = entity as PersistentPlat_util_CodeDetail;

            StringBuilder sqlUpdateSome = new StringBuilder();
            sqlUpdateSome.Append("UPDATE dbo.Plat_util_CodeDetail SET ");

            PropertyInfo[] propertyInfos = Plat_util_CodeDetailEntity.GetType().GetProperties();
            Hashtable propertyValues = new System.Collections.Hashtable();
            int columnCountForUpdate = 0;

            foreach (PropertyInfo propertyInfo in propertyInfos)
            {
                if (EntityMapping.ContainsProperty(propertyInfo.Name))
                {
                    object propertyValue = propertyInfo.GetValue(Plat_util_CodeDetailEntity, null);
                    ORProperty property = EntityMapping[propertyInfo.Name];
                    if (!property.IsPrimaryKey)
                    {
                        if (!Plat_util_CodeDetailEntity.IsDefaultValue(propertyInfo.Name))
                        {
                            propertyValues[propertyInfo.Name] = propertyValue;

                            sqlUpdateSome.Append(" " + property.ColumnName + " = @" + property.ColumnName + ",");
                            columnCountForUpdate++;
                        }
                    }
                    else
                    {
                        propertyValues[propertyInfo.Name] = propertyValue;
                    }
                }
            }
            if (columnCountForUpdate == 0)
            {
                return;
            }

            sqlUpdateSome.Remove(sqlUpdateSome.Length - 1, 1);
            sqlUpdateSome.Append(" WHERE 1 = 1 ");
            sqlUpdateSome.Append(" AND CodeDetailGuid = @CodeDetailGuid ");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(sqlUpdateSome.ToString());

                foreach (DictionaryEntry de in propertyValues)
                {
                    ORProperty property = EntityMapping[de.Key.ToString()];
                    db.AddInParameter(dbCommand, "@" + property.ColumnName, property.DatabaseType, de.Value);
                }

                int result = db.ExecuteNonQuery(dbCommand);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        /// <summary>
        /// Update with transaction
        /// </summary>

        public void Update(Plat_util_CodeDetail entity, DbTransaction transaction)
        {
            Update(entity, true, transaction);
        }

        public void Update(Plat_util_CodeDetail entity, bool updateAll, DbTransaction transaction)
        {
            if (!updateAll)
            {
                UpdateSome(entity, transaction);
            }
            else
            {
                UpdateAll(entity, transaction);
            }
        }

        private void UpdateAll(Plat_util_CodeDetail entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PersistentPlat_util_CodeDetail Plat_util_CodeDetailEntity = entity as PersistentPlat_util_CodeDetail;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(Plat_util_CodeDetailDAO.SqlUpdate);

                db.AddInParameter(dbCommand, "@CodeDetailGuid", DbType.Guid, Plat_util_CodeDetailEntity.CodeDetailGuid);
                db.AddInParameter(dbCommand, "@CodeBaseCode", DbType.String, Plat_util_CodeDetailEntity.CodeBaseCode);
                db.AddInParameter(dbCommand, "@CodeDetailCode", DbType.String, Plat_util_CodeDetailEntity.CodeDetailCode);
                db.AddInParameter(dbCommand, "@CodeDetailName", DbType.String, Plat_util_CodeDetailEntity.CodeDetailName);
                db.AddInParameter(dbCommand, "@CodeDetailDesc", DbType.String, Plat_util_CodeDetailEntity.CodeDetailDesc);
                db.AddInParameter(dbCommand, "@CodeDetailValue", DbType.String, Plat_util_CodeDetailEntity.CodeDetailValue);
                db.AddInParameter(dbCommand, "@MySequence", DbType.Int32, Plat_util_CodeDetailEntity.MySequence);
                db.AddInParameter(dbCommand, "@IsDefault", DbType.Boolean, Plat_util_CodeDetailEntity.IsDefault);
                db.AddInParameter(dbCommand, "@IsDisplay", DbType.Boolean, Plat_util_CodeDetailEntity.IsDisplay);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, Plat_util_CodeDetailEntity.IsActive);
                int result = db.ExecuteNonQuery(dbCommand, transaction);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        private void UpdateSome(Plat_util_CodeDetail entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PersistentPlat_util_CodeDetail Plat_util_CodeDetailEntity = entity as PersistentPlat_util_CodeDetail;

            StringBuilder sqlUpdateSome = new StringBuilder();
            sqlUpdateSome.Append("UPDATE dbo.Plat_util_CodeDetail SET ");

            PropertyInfo[] propertyInfos = Plat_util_CodeDetailEntity.GetType().GetProperties();
            Hashtable propertyValues = new System.Collections.Hashtable();
            int columnCountForUpdate = 0;

            foreach (PropertyInfo propertyInfo in propertyInfos)
            {
                if (EntityMapping.ContainsProperty(propertyInfo.Name))
                {
                    object propertyValue = propertyInfo.GetValue(Plat_util_CodeDetailEntity, null);
                    ORProperty property = EntityMapping[propertyInfo.Name];
                    if (!property.IsPrimaryKey)
                    {
                        if (!Plat_util_CodeDetailEntity.IsDefaultValue(propertyInfo.Name))
                        {
                            propertyValues[propertyInfo.Name] = propertyValue;

                            sqlUpdateSome.Append(" " + property.ColumnName + " = @" + property.ColumnName + ",");
                            columnCountForUpdate++;
                        }
                    }
                    else
                    {
                        propertyValues[propertyInfo.Name] = propertyValue;
                    }
                }
            }
            if (columnCountForUpdate == 0)
            {
                return;
            }

            sqlUpdateSome.Remove(sqlUpdateSome.Length - 1, 1);
            sqlUpdateSome.Append(" WHERE 1 = 1 ");
            sqlUpdateSome.Append(" AND CodeDetailGuid = @CodeDetailGuid ");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(sqlUpdateSome.ToString());

                foreach (DictionaryEntry de in propertyValues)
                {
                    ORProperty property = EntityMapping[de.Key.ToString()];
                    db.AddInParameter(dbCommand, "@" + property.ColumnName, property.DatabaseType, de.Value);
                }

                int result = db.ExecuteNonQuery(dbCommand, transaction);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        /// <summary>
        /// ORMapping
        /// </summary>

        private OREntity entityMapping;

        public OREntity EntityMapping
        {
            get
            {
                if (entityMapping == null)
                {
                    LoadMappings();
                }

                return entityMapping;
            }
        }

        private void LoadMappings()
        {
            entityMapping = new OREntity();
            entityMapping.Name = "Plat_util_CodeDetail";
            entityMapping.TableName = "dbo.Plat_util_CodeDetail";

            foreach (object[] propertyMapping in this.PropertyMappings)
            {
                ORProperty property = new ORProperty();

                property.ColumnName = (string)propertyMapping[0];
                property.DatabaseType = (DbType)propertyMapping[1];
                property.IsNullable = (bool)propertyMapping[2];
                property.IsPrimaryKey = (bool)propertyMapping[3];
                property.Name = (string)propertyMapping[4];
                property.Type = (Type)propertyMapping[5];

                entityMapping.Properties.Add(property);
            }
        }

        private object[][] PropertyMappings = new object[][] 
        {
            new object[] {"CodeDetailGuid", DbType.Guid, false, true, "CodeDetailGuid",typeof(Guid?)},
            new object[] {"CodeBaseCode", DbType.String, true, false, "CodeBaseCode",typeof(String)},
            new object[] {"CodeDetailCode", DbType.String, true, false, "CodeDetailCode",typeof(String)},
            new object[] {"CodeDetailName", DbType.String, true, false, "CodeDetailName",typeof(String)},
            new object[] {"CodeDetailDesc", DbType.String, true, false, "CodeDetailDesc",typeof(String)},
            new object[] {"CodeDetailValue", DbType.String, true, false, "CodeDetailValue",typeof(String)},
            new object[] {"MySequence", DbType.Int32, true, false, "MySequence",typeof(Int32?)},
            new object[] {"IsDefault", DbType.Boolean, true, false, "IsDefault",typeof(Boolean?)},
            new object[] {"IsDisplay", DbType.Boolean, true, false, "IsDisplay",typeof(Boolean?)},
            new object[] {"IsActive", DbType.Boolean, true, false, "IsActive",typeof(Boolean?)},
        };


        #endregion Update

        #region Find
        /// <summary>
        /// Find
        /// </summary>
        public IList<Plat_util_CodeDetail> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords)
        {
            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<Plat_util_CodeDetail> Plat_util_CodeDetailList = new List<Plat_util_CodeDetail>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY CodeDetailGuid";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, Plat_util_CodeDetailDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       Plat_util_CodeDetailDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                    {
                        while (dataReader.Read())
                        {
                            Plat_util_CodeDetailList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return Plat_util_CodeDetailList;
        }

        /// <summary>
        /// Find with transaction
        /// </summary>
        public IList<Plat_util_CodeDetail> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<Plat_util_CodeDetail> Plat_util_CodeDetailList = new List<Plat_util_CodeDetail>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY CodeDetailGuid";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, Plat_util_CodeDetailDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       Plat_util_CodeDetailDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                    {
                        while (dataReader.Read())
                        {
                            Plat_util_CodeDetailList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount, transaction));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return Plat_util_CodeDetailList;
        }

        #endregion Find

        #endregion IDataAccessor members


        #region Private Method

        private static Database GetDatabaseInstance()
        {
            return DatabaseFactory.CreateDatabase();
        }

        private static Plat_util_CodeDetail ReadEntity(IDataReader dataReader)
        {
            Plat_util_CodeDetail Plat_util_CodeDetailEntity = new Plat_util_CodeDetail();
            object value;


            value = dataReader["CodeDetailGuid"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.CodeDetailGuid = (Guid?)value;
            }

            value = dataReader["CodeBaseCode"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.CodeBaseCode = (String)value;
            }

            value = dataReader["CodeDetailCode"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.CodeDetailCode = (String)value;
            }

            value = dataReader["CodeDetailName"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.CodeDetailName = (String)value;
            }

            value = dataReader["CodeDetailDesc"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.CodeDetailDesc = (String)value;
            }

            value = dataReader["CodeDetailValue"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.CodeDetailValue = (String)value;
            }

            value = dataReader["MySequence"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.MySequence = (Int32?)value;
            }

            value = dataReader["IsDefault"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.IsDefault = (Boolean?)value;
            }

            value = dataReader["IsDisplay"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.IsDisplay = (Boolean?)value;
            }

            value = dataReader["IsActive"];
            if (value != DBNull.Value)
            {
                Plat_util_CodeDetailEntity.IsActive = (Boolean?)value;
            }

            return Plat_util_CodeDetailEntity;
        }

        #endregion Private Method

    }
}
