
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// LiXiao Info Tech Ltd. Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Globalization;

using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.Platform.Core.ORMapping;
using Siemens.Simatic.Platform.Common;
using Siemens.Simatic.Platform.Common.ExceptionHandling;
using Siemens.Simatic.Platform.Data;
using Siemens.Simatic.Platform.Data.DataAccess;

using Siemens.Simatic.ALT.Common;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.DataAccess
{
    [DefaultImplementationAttreibute(typeof(DefaultImpl.CV_PM_ALT_EVENT_TYPEDAO))]
    public interface ICV_PM_ALT_EVENT_TYPEDAO : IDataAccessor<CV_PM_ALT_EVENT_TYPE>
    {
    }
}

namespace Siemens.Simatic.ALT.DataAccess.DefaultImpl
{
    /// Title: CV_PM_ALT_EVENT_TYPEDAO
    /// Copyright: LiXiao Info Tech Ltd.
    /// Version: 1.0  
    public partial class CV_PM_ALT_EVENT_TYPEDAO : ICV_PM_ALT_EVENT_TYPEDAO
    {

        #region SQl
        #region SqlCount
        private const string SqlCount = @"SELECT COUNT(*) 
                                  FROM dbo.CV_PM_ALT_EVENT_TYPE 
                                  WHERE ( 1 = 1 {0} ) 
                                          ";
        #endregion SqlCount

        #region SqlSelectAll
        private const string SqlSelectAll = @"SELECT
                                                    [EventTypeID],
                                                    [EventTypeName],
                                                    [EventTypeDesc],
                                                    [EventPriority],
                                                    [EventBrief],
                                                    [EventContent],
                                                    [NotiCnt],
                                                    [Category],
                                                    [CreatedBy],
                                                    [CreatedOn],
                                                    [ModifiedBy],
                                                    [ModifiedOn]
                                                FROM dbo.CV_PM_ALT_EVENT_TYPE 
                                                WHERE (1 = 1 {0} ) {1}
                                        ";
        #endregion SqlSelectAll

        #region SqlSelect
        private const string SqlSelect = @"SELECT TOP {0} 
                                                [EventTypeID],
                                                [EventTypeName],
                                                [EventTypeDesc],
                                                [EventPriority],
                                                [EventBrief],
                                                [EventContent],
                                                [NotiCnt],
                                                [Category],
                                                [CreatedBy],
                                                [CreatedOn],
                                                [ModifiedBy],
                                                [ModifiedOn]
                                           FROM dbo.CV_PM_ALT_EVENT_TYPE 
                                           WHERE ( 1 = 1 {1} 
                                           AND EventTypeID 
                                           NOT IN 
                                           (SELECT TOP {2} EventTypeID 
                                           FROM dbo.CV_PM_ALT_EVENT_TYPE 
                                           WHERE (1 = 1 {3}) 
                                           {4} ) ) {5} 
                                           ";
        #endregion SqlSelect
        #endregion SQL


        #region IDataAccessor members

        #region Find
        /// <summary>
        /// Find
        /// </summary>
        public IList<CV_PM_ALT_EVENT_TYPE> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords)
        {
            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<CV_PM_ALT_EVENT_TYPE> CV_PM_ALT_EVENT_TYPEList = new List<CV_PM_ALT_EVENT_TYPE>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY EventTypeID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, CV_PM_ALT_EVENT_TYPEDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       CV_PM_ALT_EVENT_TYPEDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                    {
                        while (dataReader.Read())
                        {
                            CV_PM_ALT_EVENT_TYPEList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return CV_PM_ALT_EVENT_TYPEList;
        }

        /// <summary>
        /// Find with transaction
        /// </summary>
        public IList<CV_PM_ALT_EVENT_TYPE> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<CV_PM_ALT_EVENT_TYPE> CV_PM_ALT_EVENT_TYPEList = new List<CV_PM_ALT_EVENT_TYPE>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY EventTypeID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, CV_PM_ALT_EVENT_TYPEDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       CV_PM_ALT_EVENT_TYPEDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                    {
                        while (dataReader.Read())
                        {
                            CV_PM_ALT_EVENT_TYPEList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount,transaction));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return CV_PM_ALT_EVENT_TYPEList;
        }

        #endregion Find

        #endregion IDataAccessor members


        #region Private Method

        private static Database GetDatabaseInstance()
        {
            return DatabaseFactory.CreateDatabase(DatabaseEnum.SITBusinessDB);
        }

        private static CV_PM_ALT_EVENT_TYPE ReadEntity(IDataReader dataReader)
        {
            CV_PM_ALT_EVENT_TYPE CV_PM_ALT_EVENT_TYPEEntity = new CV_PM_ALT_EVENT_TYPE();
            object value;


            value = dataReader["EventTypeID"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.EventTypeID = (Guid?)value;
            }

            value = dataReader["EventTypeName"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.EventTypeName = (String)value;
            }

            value = dataReader["EventTypeDesc"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.EventTypeDesc = (String)value;
            }

            value = dataReader["EventPriority"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.EventPriority = (Int32?)value;
            }

            value = dataReader["EventBrief"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.EventBrief = (String)value;
            }

            value = dataReader["EventContent"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.EventContent = (String)value;
            }

            value = dataReader["NotiCnt"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.NotiCnt = (Int32?)value;
            }

            value = dataReader["Category"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.Category = (String)value;
            }

            value = dataReader["CreatedBy"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.CreatedBy = (String)value;
            }

            value = dataReader["CreatedOn"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.CreatedOn = (DateTime?)value;
            }

            value = dataReader["ModifiedBy"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.ModifiedBy = (String)value;
            }

            value = dataReader["ModifiedOn"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_EVENT_TYPEEntity.ModifiedOn = (DateTime?)value;
            }

            return CV_PM_ALT_EVENT_TYPEEntity;
        }

        #endregion Private Method


        #region NotImplemented Methods

        public CV_PM_ALT_EVENT_TYPE Insert(CV_PM_ALT_EVENT_TYPE entity)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_EVENT_TYPE Insert(CV_PM_ALT_EVENT_TYPE entity, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Delete(object entityId)
        {
            throw new NotImplementedException();
        }
        public void Delete(object entityId, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_EVENT_TYPE Get(object entityId)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_EVENT_TYPE Get(object entityId, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_EVENT_TYPE entity)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_EVENT_TYPE entity, bool updateAll)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_EVENT_TYPE entity, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_EVENT_TYPE entity, bool updateAll, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }

        #endregion NotImplemented Methods

    }
}
