
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// LiXiao Info Tech Ltd. Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Globalization;

using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.Platform.Core.ORMapping;
using Siemens.Simatic.Platform.Common;
using Siemens.Simatic.Platform.Common.ExceptionHandling;
using Siemens.Simatic.Platform.Data;
using Siemens.Simatic.Platform.Data.DataAccess;

using Siemens.Simatic.ALT.Common;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.DataAccess
{
    [DefaultImplementationAttreibute(typeof(DefaultImpl.CV_PM_ALT_CRITERION_CONDDAO))]
    public interface ICV_PM_ALT_CRITERION_CONDDAO : IDataAccessor<CV_PM_ALT_CRITERION_COND>
    {
    }
}

namespace Siemens.Simatic.ALT.DataAccess.DefaultImpl
{
    /// Title: CV_PM_ALT_CRITERION_CONDDAO
    /// Copyright: LiXiao Info Tech Ltd.
    /// Version: 1.0  
    public partial class CV_PM_ALT_CRITERION_CONDDAO : ICV_PM_ALT_CRITERION_CONDDAO
    {

        #region SQl
        #region SqlCount
        private const string SqlCount = @"SELECT COUNT(*) 
                                  FROM dbo.CV_PM_ALT_CRITERION_COND 
                                  WHERE ( 1 = 1 {0} ) 
                                          ";
        #endregion SqlCount

        #region SqlSelectAll
        private const string SqlSelectAll = @"SELECT
                                                    [ConditionID],
                                                    [AlertID],
                                                    [AlertName],
                                                    [AlertAlias],
                                                    [Relation],
                                                    [Element],
                                                    [ColumnAlias],
                                                    [Operator],
                                                    [Value],
                                                    [Sequence],
                                                    [ParentID],
                                                    [CondLevel],
                                                    [IsActive],
                                                    [CreatedBy],
                                                    [CreatedOn],
                                                    [ModifiedBy],
                                                    [ModifiedOn]
                                                FROM dbo.CV_PM_ALT_CRITERION_COND 
                                                WHERE (1 = 1 {0} ) {1}
                                        ";
        #endregion SqlSelectAll

        #region SqlSelect
        private const string SqlSelect = @"SELECT TOP {0} 
                                                [ConditionID],
                                                [AlertID],
                                                [AlertName],
                                                [AlertAlias],
                                                [Relation],
                                                [Element],
                                                [ColumnAlias],
                                                [Operator],
                                                [Value],
                                                [Sequence],
                                                [ParentID],
                                                [CondLevel],
                                                [IsActive],
                                                [CreatedBy],
                                                [CreatedOn],
                                                [ModifiedBy],
                                                [ModifiedOn]
                                           FROM dbo.CV_PM_ALT_CRITERION_COND 
                                           WHERE ( 1 = 1 {1} 
                                           AND ConditionID 
                                           NOT IN 
                                           (SELECT TOP {2} ConditionID 
                                           FROM dbo.CV_PM_ALT_CRITERION_COND 
                                           WHERE (1 = 1 {3}) 
                                           {4} ) ) {5} 
                                           ";
        #endregion SqlSelect
        #endregion SQL


        #region IDataAccessor members

        #region Find
        /// <summary>
        /// Find
        /// </summary>
        public IList<CV_PM_ALT_CRITERION_COND> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords)
        {
            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<CV_PM_ALT_CRITERION_COND> CV_PM_ALT_CRITERION_CONDList = new List<CV_PM_ALT_CRITERION_COND>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY ConditionID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, CV_PM_ALT_CRITERION_CONDDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       CV_PM_ALT_CRITERION_CONDDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                    {
                        while (dataReader.Read())
                        {
                            CV_PM_ALT_CRITERION_CONDList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return CV_PM_ALT_CRITERION_CONDList;
        }

        /// <summary>
        /// Find with transaction
        /// </summary>
        public IList<CV_PM_ALT_CRITERION_COND> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<CV_PM_ALT_CRITERION_COND> CV_PM_ALT_CRITERION_CONDList = new List<CV_PM_ALT_CRITERION_COND>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY ConditionID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, CV_PM_ALT_CRITERION_CONDDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       CV_PM_ALT_CRITERION_CONDDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                    {
                        while (dataReader.Read())
                        {
                            CV_PM_ALT_CRITERION_CONDList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount,transaction));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return CV_PM_ALT_CRITERION_CONDList;
        }

        #endregion Find

        #endregion IDataAccessor members


        #region Private Method

        private static Database GetDatabaseInstance()
        {
            return DatabaseFactory.CreateDatabase(DatabaseEnum.SITBusinessDB);
        }

        private static CV_PM_ALT_CRITERION_COND ReadEntity(IDataReader dataReader)
        {
            CV_PM_ALT_CRITERION_COND CV_PM_ALT_CRITERION_CONDEntity = new CV_PM_ALT_CRITERION_COND();
            object value;


            value = dataReader["ConditionID"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.ConditionID = (Guid?)value;
            }

            value = dataReader["AlertID"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.AlertID = (Guid?)value;
            }

            value = dataReader["AlertName"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.AlertName = (String)value;
            }

            value = dataReader["AlertAlias"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.AlertAlias = (String)value;
            }

            value = dataReader["Relation"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.Relation = (String)value;
            }

            value = dataReader["Element"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.Element = (String)value;
            }

            value = dataReader["ColumnAlias"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.ColumnAlias = (String)value;
            }

            value = dataReader["Operator"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.Operator = (String)value;
            }

            value = dataReader["Value"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.Value = (String)value;
            }

            value = dataReader["Sequence"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.Sequence = (Int32?)value;
            }

            value = dataReader["ParentID"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.ParentID = (Guid?)value;
            }

            value = dataReader["CondLevel"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.CondLevel = (Int32?)value;
            }

            value = dataReader["IsActive"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.IsActive = (Boolean?)value;
            }

            value = dataReader["CreatedBy"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.CreatedBy = (String)value;
            }

            value = dataReader["CreatedOn"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.CreatedOn = (DateTime?)value;
            }

            value = dataReader["ModifiedBy"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.ModifiedBy = (String)value;
            }

            value = dataReader["ModifiedOn"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_CRITERION_CONDEntity.ModifiedOn = (DateTime?)value;
            }

            return CV_PM_ALT_CRITERION_CONDEntity;
        }

        #endregion Private Method


        #region NotImplemented Methods

        public CV_PM_ALT_CRITERION_COND Insert(CV_PM_ALT_CRITERION_COND entity)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_CRITERION_COND Insert(CV_PM_ALT_CRITERION_COND entity, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Delete(object entityId)
        {
            throw new NotImplementedException();
        }
        public void Delete(object entityId, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_CRITERION_COND Get(object entityId)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_CRITERION_COND Get(object entityId, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_CRITERION_COND entity)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_CRITERION_COND entity, bool updateAll)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_CRITERION_COND entity, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_CRITERION_COND entity, bool updateAll, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }

        #endregion NotImplemented Methods

    }
}
