
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Globalization;

using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.Platform.Core.ORMapping;
using Siemens.Simatic.Platform.Common;
using Siemens.Simatic.Platform.Common.ExceptionHandling;
using Siemens.Simatic.Platform.Data;
using Siemens.Simatic.Platform.Data.DataAccess;

using Siemens.Simatic.ALT.Common;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.DataAccess
{
    [DefaultImplementationAttreibute(typeof(DefaultImpl.CV_PM_ALT_BASEDAO))]
    public interface ICV_PM_ALT_BASEDAO : IDataAccessor<CV_PM_ALT_BASE>
    {
    }
}

namespace Siemens.Simatic.ALT.DataAccess.DefaultImpl
{
    /// Title: CV_PM_ALT_BASEDAO
    /// Copyright: Siemens
    /// Version: 1.0  
    public partial class CV_PM_ALT_BASEDAO : ICV_PM_ALT_BASEDAO
    {

        #region SQl
        #region SqlCount
        private const string SqlCount = @"SELECT COUNT(*) 
                                  FROM dbo.CV_PM_ALT_BASE 
                                  WHERE ( 1 = 1 {0} ) 
                                          ";
        #endregion SqlCount

        #region SqlSelectAll
        private const string SqlSelectAll = @"SELECT
                                                    [AlertID],
                                                    [AlertName],
                                                    [AlertAlias],
                                                    [SqlScript],
                                                    [URL],
                                                    [AlertDesc],
                                                    [AlertContent],
                                                    [Category],
                                                    [AlertType],
                                                    [Format],
                                                    [AlertObject],
                                                    [PreProcedure],
                                                    [PostProcedure],
                                                    [AlertInterval],
                                                    [AlertTimePoints],
                                                    [LastAlertedTime],
                                                    [IsActive],
                                                    [CIsActive],
                                                    [RowDeleted],
                                                    [CreatedBy],
                                                    [CreatedOn],
                                                    [ModifiedBy],
                                                    [ModifiedOn]
                                                FROM dbo.CV_PM_ALT_BASE 
                                                WHERE (1 = 1 {0} ) {1}
                                        ";
        #endregion SqlSelectAll

        #region SqlSelect
        private const string SqlSelect = @"SELECT TOP {0} 
                                                [AlertID],
                                                [AlertName],
                                                [AlertAlias],
                                                [SqlScript],
                                                [URL],
                                                [AlertDesc],
                                                [AlertContent],
                                                [Category],
                                                [AlertType],
                                                [Format],
                                                [AlertObject],
                                                [PreProcedure],
                                                [PostProcedure],
                                                [AlertInterval],
                                                [AlertTimePoints],
                                                [LastAlertedTime],
                                                [IsActive],
                                                [CIsActive],
                                                [RowDeleted],
                                                [CreatedBy],
                                                [CreatedOn],
                                                [ModifiedBy],
                                                [ModifiedOn]
                                           FROM dbo.CV_PM_ALT_BASE 
                                           WHERE ( 1 = 1 {1} 
                                           AND AlertID 
                                           NOT IN 
                                           (SELECT TOP {2} AlertID 
                                           FROM dbo.CV_PM_ALT_BASE 
                                           WHERE (1 = 1 {3}) 
                                           {4} ) ) {5} 
                                           ";
        #endregion SqlSelect    
        #endregion SQL


        #region IDataAccessor members

        #region Find
        /// <summary>
        /// Find
        /// </summary>
        public IList<CV_PM_ALT_BASE> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords)
        {
            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<CV_PM_ALT_BASE> CV_PM_ALT_BASEList = new List<CV_PM_ALT_BASE>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY AlertID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, CV_PM_ALT_BASEDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       CV_PM_ALT_BASEDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                    {
                        while (dataReader.Read())
                        {
                            CV_PM_ALT_BASEList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return CV_PM_ALT_BASEList;
        }

        /// <summary>
        /// Find with transaction
        /// </summary>
        public IList<CV_PM_ALT_BASE> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<CV_PM_ALT_BASE> CV_PM_ALT_BASEList = new List<CV_PM_ALT_BASE>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY AlertID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, CV_PM_ALT_BASEDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       CV_PM_ALT_BASEDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                    {
                        while (dataReader.Read())
                        {
                            CV_PM_ALT_BASEList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount,transaction));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return CV_PM_ALT_BASEList;
        }

        #endregion Find

        #endregion IDataAccessor members


        #region Private Method

        private static Database GetDatabaseInstance()
        {
            return DatabaseFactory.CreateDatabase(DatabaseEnum.SITBusinessDB);
        }

        private static CV_PM_ALT_BASE ReadEntity(IDataReader dataReader)
        {
            CV_PM_ALT_BASE CV_PM_ALT_BASEEntity = new CV_PM_ALT_BASE();
            object value;


            value = dataReader["AlertID"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertID = (Guid?)value;
            }

            value = dataReader["AlertName"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertName = (String)value;
            }

            value = dataReader["AlertAlias"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertAlias = (String)value;
            }

            value = dataReader["SqlScript"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.SqlScript = (String)value;
            }

            value = dataReader["URL"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.URL = (String)value;
            }

            value = dataReader["AlertDesc"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertDesc = (String)value;
            }

            value = dataReader["AlertContent"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertContent = (String)value;
            }

            value = dataReader["Category"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.Category = (String)value;
            }

            value = dataReader["AlertType"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertType = (Int32?)value;
            }

            value = dataReader["Format"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.Format = (String)value;
            }

            value = dataReader["AlertObject"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertObject = (String)value;
            }

            value = dataReader["PreProcedure"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.PreProcedure = (String)value;
            }

            value = dataReader["PostProcedure"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.PostProcedure = (String)value;
            }

            value = dataReader["AlertInterval"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertInterval = (Int32?)value;
            }

            value = dataReader["AlertTimePoints"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.AlertTimePoints = (String)value;
            }

            value = dataReader["LastAlertedTime"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.LastAlertedTime = (DateTime?)value;
            }

            value = dataReader["IsActive"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.IsActive = (Boolean?)value;
            }

            value = dataReader["CIsActive"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.CIsActive = (String)value;
            }

            value = dataReader["RowDeleted"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.RowDeleted = (Boolean?)value;
            }

            value = dataReader["CreatedBy"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.CreatedBy = (String)value;
            }

            value = dataReader["CreatedOn"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.CreatedOn = (DateTime?)value;
            }

            value = dataReader["ModifiedBy"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.ModifiedBy = (String)value;
            }

            value = dataReader["ModifiedOn"];
            if (value != DBNull.Value)
            {
                CV_PM_ALT_BASEEntity.ModifiedOn = (DateTime?)value;
            }

            return CV_PM_ALT_BASEEntity;
        }

        #endregion Private Method


        #region NotImplemented Methods

        public CV_PM_ALT_BASE Insert(CV_PM_ALT_BASE entity)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_BASE Insert(CV_PM_ALT_BASE entity, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Delete(object entityId)
        {
            throw new NotImplementedException();
        }
        public void Delete(object entityId, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_BASE Get(object entityId)
        {
            throw new NotImplementedException();
        }
        public CV_PM_ALT_BASE Get(object entityId, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_BASE entity)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_BASE entity, bool updateAll)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_BASE entity, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }
        public void Update(CV_PM_ALT_BASE entity, bool updateAll, DbTransaction transaction)
        {
            throw new NotImplementedException();
        }

        #endregion NotImplemented Methods

    }
}
