
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// LiXiao Info Tech Ltd. Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Globalization;

using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.Platform.Core.ORMapping;
using Siemens.Simatic.Platform.Common;
using Siemens.Simatic.Platform.Common.ExceptionHandling;
using Siemens.Simatic.Platform.Data;
using Siemens.Simatic.Platform.Data.DataAccess;

using Siemens.Simatic.ALT.Common;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.DataAccess
{
    [DefaultImplementationAttreibute(typeof(DefaultImpl.PM_ALT_NOTI_GROUP_DETAILDAO))]
    public partial interface IPM_ALT_NOTI_GROUP_DETAILDAO : IDataAccessor<PM_ALT_NOTI_GROUP_DETAIL>
    {
    }
}

namespace Siemens.Simatic.ALT.DataAccess.DefaultImpl
{
    /// Title: PM_ALT_NOTI_GROUP_DETAILDAO
    /// Copyright: LiXiao Info Tech Ltd.
    /// Version: 1.0  
    public partial class PM_ALT_NOTI_GROUP_DETAILDAO : IPM_ALT_NOTI_GROUP_DETAILDAO
    {

        #region SQl
        #region SqlInsert
        private const string SqlInsert = @"INSERT INTO dbo.PM_ALT_NOTI_GROUP_DETAIL (
                                                [NotiGroupDetailID],
                                                [NotiGroupID],
                                                [SubGroupID],
                                                [MemberID],
                                                [RowDeleted]
                                                ) VALUES ( 
                                                @NotiGroupDetailID,
                                                @NotiGroupID,
                                                @SubGroupID,
                                                @MemberID,
                                                @RowDeleted
                                            )";
        #endregion

        #region SqlDelete
        private const string SqlDelete = @"DELETE FROM dbo.PM_ALT_NOTI_GROUP_DETAIL 
                                           WHERE 1 = 1 
                                           AND NotiGroupDetailID = @NotiGroupDetailID";
        #endregion

        #region SqlUpdateAll
        private const string SqlUpdate = @"UPDATE dbo.PM_ALT_NOTI_GROUP_DETAIL SET
                                            [NotiGroupID] = @NotiGroupID,
                                            [SubGroupID] = @SubGroupID,
                                            [MemberID] = @MemberID,
                                            [RowDeleted] = @RowDeleted
                                            WHERE 1 = 1
                                            AND [NotiGroupDetailID] = @NotiGroupDetailID";
        #endregion

        #region SqlGet
        private const string SqlGet = @"SELECT
                                            [NotiGroupDetailID],
                                            [NotiGroupID],
                                            [SubGroupID],
                                            [MemberID],
                                            [RowDeleted]
                                        FROM dbo.PM_ALT_NOTI_GROUP_DETAIL
                                        WHERE 1 = 1 
                                        AND [NotiGroupDetailID] = @NotiGroupDetailID";
        #endregion

        #region SqlCount
        private const string SqlCount = @"SELECT COUNT(*) 
                                  FROM dbo.PM_ALT_NOTI_GROUP_DETAIL 
                                  WHERE ( 1 = 1 {0} ) 
                                          ";
        #endregion SqlCount

        #region SqlSelectAll
        private const string SqlSelectAll = @"SELECT
                                                    [NotiGroupDetailID],
                                                    [NotiGroupID],
                                                    [SubGroupID],
                                                    [MemberID],
                                                    [RowDeleted]
                                                FROM dbo.PM_ALT_NOTI_GROUP_DETAIL 
                                                WHERE (1 = 1 {0} ) {1}
                                        ";
        #endregion SqlSelectAll

        #region SqlSelect
        private const string SqlSelect = @"SELECT TOP {0} 
                                                [NotiGroupDetailID],
                                                [NotiGroupID],
                                                [SubGroupID],
                                                [MemberID],
                                                [RowDeleted]
                                           FROM dbo.PM_ALT_NOTI_GROUP_DETAIL 
                                           WHERE ( 1 = 1 {1} 
                                           AND NotiGroupDetailID 
                                           NOT IN 
                                           (SELECT TOP {2} NotiGroupDetailID 
                                           FROM dbo.PM_ALT_NOTI_GROUP_DETAIL 
                                           WHERE (1 = 1 {3}) 
                                           {4} ) ) {5} 
                                           ";
        #endregion SqlSelect
        #endregion SQL


        #region IDataAccessor members

        #region Insert
        /// <summary>
        /// Insert 
        /// </summary>  
        public PM_ALT_NOTI_GROUP_DETAIL Insert(PM_ALT_NOTI_GROUP_DETAIL entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            PersistentPM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = entity as PersistentPM_ALT_NOTI_GROUP_DETAIL;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlInsert);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupDetailID);
                db.AddInParameter(dbCommand, "@NotiGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupID);
                db.AddInParameter(dbCommand, "@SubGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.SubGroupID);
                db.AddInParameter(dbCommand, "@MemberID", DbType.String, PM_ALT_NOTI_GROUP_DETAILEntity.MemberID);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_NOTI_GROUP_DETAILEntity.RowDeleted);

                int result = db.ExecuteNonQuery(dbCommand);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_NOTI_GROUP_DETAILEntity as PM_ALT_NOTI_GROUP_DETAIL;
        }

        /// <summary>
        /// Insert with transaction
        /// </summary>  
        public PM_ALT_NOTI_GROUP_DETAIL Insert(PM_ALT_NOTI_GROUP_DETAIL entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");
            PersistentPM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = entity as PersistentPM_ALT_NOTI_GROUP_DETAIL;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlInsert);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupDetailID);
                db.AddInParameter(dbCommand, "@NotiGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupID);
                db.AddInParameter(dbCommand, "@SubGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.SubGroupID);
                db.AddInParameter(dbCommand, "@MemberID", DbType.String, PM_ALT_NOTI_GROUP_DETAILEntity.MemberID);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_NOTI_GROUP_DETAILEntity.RowDeleted);

                int result = db.ExecuteNonQuery(dbCommand, transaction);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_NOTI_GROUP_DETAILEntity as PM_ALT_NOTI_GROUP_DETAIL;
        }

        #endregion Insert

        #region Delete
        /// <summary>
        /// Delete 
        /// </summary>  
        public void Delete(object entityId)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlDelete);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, entityId);
                int result = db.ExecuteNonQuery(dbCommand);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }


        /// <summary>
        /// Delete with transaction
        /// </summary>  
        public void Delete(object entityId, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlDelete);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, entityId);
                int result = db.ExecuteNonQuery(dbCommand, transaction);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        #endregion Delete

        #region Get
        /// <summary>
        /// Get
        /// </summary>
        public PM_ALT_NOTI_GROUP_DETAIL Get(object entityId)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");

            PM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = null;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlGet);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, entityId);
                using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                {
                    if (dataReader.Read())
                    {
                        PM_ALT_NOTI_GROUP_DETAILEntity = ReadEntity(dataReader);
                    }
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_NOTI_GROUP_DETAILEntity;
        }


        /// <summary>
        /// Get with transaction
        /// </summary>
        public PM_ALT_NOTI_GROUP_DETAIL Get(object entityId, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = null;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlGet);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, entityId);
                using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                {
                    if (dataReader.Read())
                    {
                        PM_ALT_NOTI_GROUP_DETAILEntity = ReadEntity(dataReader);
                    }
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_NOTI_GROUP_DETAILEntity;
        }

        #endregion Get

        #region Update

        /// <summary>
        /// Update
        /// </summary>

        public void Update(PM_ALT_NOTI_GROUP_DETAIL entity)
        {
            Update(entity, true);
        }

        public void Update(PM_ALT_NOTI_GROUP_DETAIL entity, bool updateAll)
        {
            if (!updateAll)
            {
                UpdateSome(entity);
            }
            else
            {
                UpdateAll(entity);
            }
        }

        private void UpdateAll(PM_ALT_NOTI_GROUP_DETAIL entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");

            PersistentPM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = entity as PersistentPM_ALT_NOTI_GROUP_DETAIL;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlUpdate);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupDetailID);
                db.AddInParameter(dbCommand, "@NotiGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupID);
                db.AddInParameter(dbCommand, "@SubGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.SubGroupID);
                db.AddInParameter(dbCommand, "@MemberID", DbType.String, PM_ALT_NOTI_GROUP_DETAILEntity.MemberID);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_NOTI_GROUP_DETAILEntity.RowDeleted);
                int result = db.ExecuteNonQuery(dbCommand);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        private void UpdateSome(PM_ALT_NOTI_GROUP_DETAIL entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");

            PersistentPM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = entity as PersistentPM_ALT_NOTI_GROUP_DETAIL;

            StringBuilder sqlUpdateSome = new StringBuilder();
            sqlUpdateSome.Append("UPDATE dbo.PM_ALT_NOTI_GROUP_DETAIL SET ");

            PropertyInfo[] propertyInfos = PM_ALT_NOTI_GROUP_DETAILEntity.GetType().GetProperties();
            Hashtable propertyValues = new System.Collections.Hashtable();
            int columnCountForUpdate = 0;

            foreach (PropertyInfo propertyInfo in propertyInfos)
            {
                if (EntityMapping.ContainsProperty(propertyInfo.Name))
                {
                    object propertyValue = propertyInfo.GetValue(PM_ALT_NOTI_GROUP_DETAILEntity, null);
                    ORProperty property = EntityMapping[propertyInfo.Name];
                    if (!property.IsPrimaryKey)
                    {
                        if (!PM_ALT_NOTI_GROUP_DETAILEntity.IsDefaultValue(propertyInfo.Name))
                        {
                            propertyValues[propertyInfo.Name] = propertyValue;

                            sqlUpdateSome.Append(" " + property.ColumnName + " = @" + property.ColumnName + ",");
                            columnCountForUpdate++;
                        }
                    }
                    else
                    {
                        propertyValues[propertyInfo.Name] = propertyValue;
                    }
                }
            }
            if (columnCountForUpdate == 0)
            {
                return;
            }

            sqlUpdateSome.Remove(sqlUpdateSome.Length - 1, 1);
            sqlUpdateSome.Append(" WHERE 1 = 1 ");
            sqlUpdateSome.Append(" AND NotiGroupDetailID = @NotiGroupDetailID ");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(sqlUpdateSome.ToString());

                foreach (DictionaryEntry de in propertyValues)
                {
                    ORProperty property = EntityMapping[de.Key.ToString()];
                    db.AddInParameter(dbCommand, "@" + property.ColumnName, property.DatabaseType, de.Value);
                }

                int result = db.ExecuteNonQuery(dbCommand);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        /// <summary>
        /// Update with transaction
        /// </summary>

        public void Update(PM_ALT_NOTI_GROUP_DETAIL entity, DbTransaction transaction)
        {
            Update(entity, true, transaction);
        }

        public void Update(PM_ALT_NOTI_GROUP_DETAIL entity, bool updateAll, DbTransaction transaction)
        {
            if (!updateAll)
            {
                UpdateSome(entity, transaction);
            }
            else
            {
                UpdateAll(entity, transaction);
            }
        }

        private void UpdateAll(PM_ALT_NOTI_GROUP_DETAIL entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PersistentPM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = entity as PersistentPM_ALT_NOTI_GROUP_DETAIL;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_NOTI_GROUP_DETAILDAO.SqlUpdate);

                db.AddInParameter(dbCommand, "@NotiGroupDetailID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupDetailID);
                db.AddInParameter(dbCommand, "@NotiGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupID);
                db.AddInParameter(dbCommand, "@SubGroupID", DbType.Guid, PM_ALT_NOTI_GROUP_DETAILEntity.SubGroupID);
                db.AddInParameter(dbCommand, "@MemberID", DbType.String, PM_ALT_NOTI_GROUP_DETAILEntity.MemberID);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_NOTI_GROUP_DETAILEntity.RowDeleted);
                int result = db.ExecuteNonQuery(dbCommand, transaction);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        private void UpdateSome(PM_ALT_NOTI_GROUP_DETAIL entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PersistentPM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = entity as PersistentPM_ALT_NOTI_GROUP_DETAIL;

            StringBuilder sqlUpdateSome = new StringBuilder();
            sqlUpdateSome.Append("UPDATE dbo.PM_ALT_NOTI_GROUP_DETAIL SET ");

            PropertyInfo[] propertyInfos = PM_ALT_NOTI_GROUP_DETAILEntity.GetType().GetProperties();
            Hashtable propertyValues = new System.Collections.Hashtable();
            int columnCountForUpdate = 0;

            foreach (PropertyInfo propertyInfo in propertyInfos)
            {
                if (EntityMapping.ContainsProperty(propertyInfo.Name))
                {
                    object propertyValue = propertyInfo.GetValue(PM_ALT_NOTI_GROUP_DETAILEntity, null);
                    ORProperty property = EntityMapping[propertyInfo.Name];
                    if (!property.IsPrimaryKey)
                    {
                        if (!PM_ALT_NOTI_GROUP_DETAILEntity.IsDefaultValue(propertyInfo.Name))
                        {
                            propertyValues[propertyInfo.Name] = propertyValue;

                            sqlUpdateSome.Append(" " + property.ColumnName + " = @" + property.ColumnName + ",");
                            columnCountForUpdate++;
                        }
                    }
                    else
                    {
                        propertyValues[propertyInfo.Name] = propertyValue;
                    }
                }
            }
            if (columnCountForUpdate == 0)
            {
                return;
            }

            sqlUpdateSome.Remove(sqlUpdateSome.Length - 1, 1);
            sqlUpdateSome.Append(" WHERE 1 = 1 ");
            sqlUpdateSome.Append(" AND NotiGroupDetailID = @NotiGroupDetailID ");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(sqlUpdateSome.ToString());

                foreach (DictionaryEntry de in propertyValues)
                {
                    ORProperty property = EntityMapping[de.Key.ToString()];
                    db.AddInParameter(dbCommand, "@" + property.ColumnName, property.DatabaseType, de.Value);
                }

                int result = db.ExecuteNonQuery(dbCommand, transaction);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        /// <summary>
        /// ORMapping
        /// </summary>

        private OREntity entityMapping;

        public OREntity EntityMapping
        {
            get
            {
                if (entityMapping == null)
                {
                    LoadMappings();
                }

                return entityMapping;
            }
        }

        private void LoadMappings()
        {
            entityMapping = new OREntity();
            entityMapping.Name = "PM_ALT_NOTI_GROUP_DETAIL";
            entityMapping.TableName = "dbo.PM_ALT_NOTI_GROUP_DETAIL";

            foreach (object[] propertyMapping in this.PropertyMappings)
            {
                ORProperty property = new ORProperty();

                property.ColumnName = (string)propertyMapping[0];
                property.DatabaseType = (DbType)propertyMapping[1];
                property.IsNullable = (bool)propertyMapping[2];
                property.IsPrimaryKey = (bool)propertyMapping[3];
                property.Name = (string)propertyMapping[4];
                property.Type = (Type)propertyMapping[5];

                entityMapping.Properties.Add(property);
            }
        }

        private object[][] PropertyMappings = new object[][] 
        {
            new object[] {"NotiGroupDetailID", DbType.Guid, false, true, "NotiGroupDetailID",typeof(Guid?)},
            new object[] {"NotiGroupID", DbType.Guid, false, false, "NotiGroupID",typeof(Guid?)},
            new object[] {"SubGroupID", DbType.Guid, true, false, "SubGroupID",typeof(Guid?)},
            new object[] {"MemberID", DbType.String, true, false, "MemberID",typeof(String)},
            new object[] {"RowDeleted", DbType.Boolean, false, false, "RowDeleted",typeof(Boolean?)},
        };


        #endregion Update

        #region Find
        /// <summary>
        /// Find
        /// </summary>
        public IList<PM_ALT_NOTI_GROUP_DETAIL> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords)
        {
            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<PM_ALT_NOTI_GROUP_DETAIL> PM_ALT_NOTI_GROUP_DETAILList = new List<PM_ALT_NOTI_GROUP_DETAIL>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY NotiGroupDetailID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, PM_ALT_NOTI_GROUP_DETAILDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       PM_ALT_NOTI_GROUP_DETAILDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                    {
                        while (dataReader.Read())
                        {
                            PM_ALT_NOTI_GROUP_DETAILList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_NOTI_GROUP_DETAILList;
        }

        /// <summary>
        /// Find with transaction
        /// </summary>
        public IList<PM_ALT_NOTI_GROUP_DETAIL> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<PM_ALT_NOTI_GROUP_DETAIL> PM_ALT_NOTI_GROUP_DETAILList = new List<PM_ALT_NOTI_GROUP_DETAIL>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY NotiGroupDetailID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, PM_ALT_NOTI_GROUP_DETAILDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       PM_ALT_NOTI_GROUP_DETAILDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                    {
                        while (dataReader.Read())
                        {
                            PM_ALT_NOTI_GROUP_DETAILList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount, transaction));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_NOTI_GROUP_DETAILList;
        }

        #endregion Find

        #endregion IDataAccessor members


        #region Private Method

        private static Database GetDatabaseInstance()
        {
            return DatabaseFactory.CreateDatabase(DatabaseEnum.SITBusinessDB);
        }

        private static PM_ALT_NOTI_GROUP_DETAIL ReadEntity(IDataReader dataReader)
        {
            PM_ALT_NOTI_GROUP_DETAIL PM_ALT_NOTI_GROUP_DETAILEntity = new PM_ALT_NOTI_GROUP_DETAIL();
            object value;


            value = dataReader["NotiGroupDetailID"];
            if (value != DBNull.Value)
            {
                PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupDetailID = (Guid?)value;
            }

            value = dataReader["NotiGroupID"];
            if (value != DBNull.Value)
            {
                PM_ALT_NOTI_GROUP_DETAILEntity.NotiGroupID = (Guid?)value;
            }

            value = dataReader["SubGroupID"];
            if (value != DBNull.Value)
            {
                PM_ALT_NOTI_GROUP_DETAILEntity.SubGroupID = (Guid?)value;
            }

            value = dataReader["MemberID"];
            if (value != DBNull.Value)
            {
                PM_ALT_NOTI_GROUP_DETAILEntity.MemberID = (String)value;
            }

            value = dataReader["RowDeleted"];
            if (value != DBNull.Value)
            {
                PM_ALT_NOTI_GROUP_DETAILEntity.RowDeleted = (Boolean?)value;
            }

            return PM_ALT_NOTI_GROUP_DETAILEntity;
        }

        #endregion Private Method

    }
}
