
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;
using System.Globalization;

using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.Platform.Core.ORMapping;
using Siemens.Simatic.Platform.Common;
using Siemens.Simatic.Platform.Common.ExceptionHandling;
using Siemens.Simatic.Platform.Data;
using Siemens.Simatic.Platform.Data.DataAccess;

using Siemens.Simatic.ALT.Common;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.DataAccess
{
    [DefaultImplementationAttreibute(typeof(DefaultImpl.PM_ALT_BASEDAO))]
    public partial interface IPM_ALT_BASEDAO : IDataAccessor<PM_ALT_BASE>
    {
    }
}

namespace Siemens.Simatic.ALT.DataAccess.DefaultImpl
{
    /// Title: PM_ALT_BASEDAO
    /// Copyright: Siemens
    /// Version: 1.0  
    public partial class PM_ALT_BASEDAO : IPM_ALT_BASEDAO
    {

        #region SQl
        #region SqlInsert
        private const string SqlInsert = @"INSERT INTO dbo.PM_ALT_BASE (
                                                [AlertID],
                                                [AlertName],
                                                [AlertAlias],
                                                [SqlScript],
                                                [URL],
                                                [AlertDesc],
                                                [AlertContent],
                                                [Category],
                                                [AlertType],
                                                [Format],
                                                [AlertObject],
                                                [PreProcedure],
                                                [PostProcedure],
                                                [AlertInterval],
                                                [AlertTimePoints],
                                                [LastAlertedTime],
                                                [IsActive],
                                                [RowDeleted],
                                                [CreatedBy],
                                                [CreatedOn],
                                                [ModifiedBy],
                                                [ModifiedOn]
                                                ) VALUES ( 
                                                @AlertID,
                                                @AlertName,
                                                @AlertAlias,
                                                @SqlScript,
                                                @URL,
                                                @AlertDesc,
                                                @AlertContent,
                                                @Category,
                                                @AlertType,
                                                @Format,
                                                @AlertObject,
                                                @PreProcedure,
                                                @PostProcedure,
                                                @AlertInterval,
                                                @AlertTimePoints,
                                                @LastAlertedTime,
                                                @IsActive,
                                                @RowDeleted,
                                                @CreatedBy,
                                                @CreatedOn,
                                                @ModifiedBy,
                                                @ModifiedOn
                                            )";
        #endregion

        #region SqlDelete
        private const string SqlDelete = @"DELETE FROM dbo.PM_ALT_BASE 
                                           WHERE 1 = 1 
                                           AND AlertID = @AlertID";
        #endregion

        #region SqlUpdateAll
        private const string SqlUpdate = @"UPDATE dbo.PM_ALT_BASE SET
                                            [AlertName] = @AlertName,
                                            [AlertAlias] = @AlertAlias,
                                            [SqlScript] = @SqlScript,
                                            [URL] = @URL,
                                            [AlertDesc] = @AlertDesc,
                                            [AlertContent] = @AlertContent,
                                            [Category] = @Category,
                                            [AlertType] = @AlertType,
                                            [Format] = @Format,
                                            [AlertObject] = @AlertObject,
                                            [PreProcedure] = @PreProcedure,
                                            [PostProcedure] = @PostProcedure,
                                            [AlertInterval] = @AlertInterval,
                                            [AlertTimePoints] = @AlertTimePoints,
                                            [LastAlertedTime] = @LastAlertedTime,
                                            [IsActive] = @IsActive,
                                            [RowDeleted] = @RowDeleted,
                                            [CreatedBy] = @CreatedBy,
                                            [CreatedOn] = @CreatedOn,
                                            [ModifiedBy] = @ModifiedBy,
                                            [ModifiedOn] = @ModifiedOn
                                            WHERE 1 = 1
                                            AND [AlertID] = @AlertID";
        #endregion

        #region SqlGet
        private const string SqlGet = @"SELECT
                                            [AlertID],
                                            [AlertName],
                                            [AlertAlias],
                                            [SqlScript],
                                            [URL],
                                            [AlertDesc],
                                            [AlertContent],
                                            [Category],
                                            [AlertType],
                                            [Format],
                                            [AlertObject],
                                            [PreProcedure],
                                            [PostProcedure],
                                            [AlertInterval],
                                            [AlertTimePoints],
                                            [LastAlertedTime],
                                            [IsActive],
                                            [RowDeleted],
                                            [CreatedBy],
                                            [CreatedOn],
                                            [ModifiedBy],
                                            [ModifiedOn]
                                        FROM dbo.PM_ALT_BASE
                                        WHERE 1 = 1 
                                        AND [AlertID] = @AlertID";
        #endregion

        #region SqlCount
        private const string SqlCount = @"SELECT COUNT(*) 
                                  FROM dbo.PM_ALT_BASE 
                                  WHERE ( 1 = 1 {0} ) 
                                          ";
        #endregion SqlCount

        #region SqlSelectAll
        private const string SqlSelectAll = @"SELECT
                                                    [AlertID],
                                                    [AlertName],
                                                    [AlertAlias],
                                                    [SqlScript],
                                                    [URL],
                                                    [AlertDesc],
                                                    [AlertContent],
                                                    [Category],
                                                    [AlertType],
                                                    [Format],
                                                    [AlertObject],
                                                    [PreProcedure],
                                                    [PostProcedure],
                                                    [AlertInterval],
                                                    [AlertTimePoints],
                                                    [LastAlertedTime],
                                                    [IsActive],
                                                    [RowDeleted],
                                                    [CreatedBy],
                                                    [CreatedOn],
                                                    [ModifiedBy],
                                                    [ModifiedOn]
                                                FROM dbo.PM_ALT_BASE 
                                                WHERE (1 = 1 {0} ) {1}
                                        ";
        #endregion SqlSelectAll

        #region SqlSelect
        private const string SqlSelect = @"SELECT TOP {0} 
                                                [AlertID],
                                                [AlertName],
                                                [AlertAlias],
                                                [SqlScript],
                                                [URL],
                                                [AlertDesc],
                                                [AlertContent],
                                                [Category],
                                                [AlertType],
                                                [Format],
                                                [AlertObject],
                                                [PreProcedure],
                                                [PostProcedure],
                                                [AlertInterval],
                                                [AlertTimePoints],
                                                [LastAlertedTime],
                                                [IsActive],
                                                [RowDeleted],
                                                [CreatedBy],
                                                [CreatedOn],
                                                [ModifiedBy],
                                                [ModifiedOn]
                                           FROM dbo.PM_ALT_BASE 
                                           WHERE ( 1 = 1 {1} 
                                           AND AlertID 
                                           NOT IN 
                                           (SELECT TOP {2} AlertID 
                                           FROM dbo.PM_ALT_BASE 
                                           WHERE (1 = 1 {3}) 
                                           {4} ) ) {5} 
                                           ";
        #endregion SqlSelect
        #endregion SQL


        #region IDataAccessor members

        #region Insert
        /// <summary>
        /// Insert 
        /// </summary>  
        public PM_ALT_BASE Insert(PM_ALT_BASE entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            PersistentPM_ALT_BASE PM_ALT_BASEEntity = entity as PersistentPM_ALT_BASE;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlInsert);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, PM_ALT_BASEEntity.AlertID);
                db.AddInParameter(dbCommand, "@AlertName", DbType.String, PM_ALT_BASEEntity.AlertName);
                db.AddInParameter(dbCommand, "@AlertAlias", DbType.String, PM_ALT_BASEEntity.AlertAlias);
                db.AddInParameter(dbCommand, "@SqlScript", DbType.String, PM_ALT_BASEEntity.SqlScript);
                db.AddInParameter(dbCommand, "@URL", DbType.String, PM_ALT_BASEEntity.URL);
                db.AddInParameter(dbCommand, "@AlertDesc", DbType.String, PM_ALT_BASEEntity.AlertDesc);
                db.AddInParameter(dbCommand, "@AlertContent", DbType.String, PM_ALT_BASEEntity.AlertContent);
                db.AddInParameter(dbCommand, "@Category", DbType.String, PM_ALT_BASEEntity.Category);
                db.AddInParameter(dbCommand, "@AlertType", DbType.Int32, PM_ALT_BASEEntity.AlertType);
                db.AddInParameter(dbCommand, "@Format", DbType.String, PM_ALT_BASEEntity.Format);
                db.AddInParameter(dbCommand, "@AlertObject", DbType.String, PM_ALT_BASEEntity.AlertObject);
                db.AddInParameter(dbCommand, "@PreProcedure", DbType.String, PM_ALT_BASEEntity.PreProcedure);
                db.AddInParameter(dbCommand, "@PostProcedure", DbType.String, PM_ALT_BASEEntity.PostProcedure);
                db.AddInParameter(dbCommand, "@AlertInterval", DbType.Int32, PM_ALT_BASEEntity.AlertInterval);
                db.AddInParameter(dbCommand, "@AlertTimePoints", DbType.String, PM_ALT_BASEEntity.AlertTimePoints);
                db.AddInParameter(dbCommand, "@LastAlertedTime", DbType.DateTime, PM_ALT_BASEEntity.LastAlertedTime);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, PM_ALT_BASEEntity.IsActive);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_BASEEntity.RowDeleted);
                db.AddInParameter(dbCommand, "@CreatedBy", DbType.String, PM_ALT_BASEEntity.CreatedBy);
                db.AddInParameter(dbCommand, "@CreatedOn", DbType.DateTime, PM_ALT_BASEEntity.CreatedOn);
                db.AddInParameter(dbCommand, "@ModifiedBy", DbType.String, PM_ALT_BASEEntity.ModifiedBy);
                db.AddInParameter(dbCommand, "@ModifiedOn", DbType.DateTime, PM_ALT_BASEEntity.ModifiedOn);

                int result = db.ExecuteNonQuery(dbCommand);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_BASEEntity as PM_ALT_BASE;
        }

        /// <summary>
        /// Insert with transaction
        /// </summary>  
        public PM_ALT_BASE Insert(PM_ALT_BASE entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");
            PersistentPM_ALT_BASE PM_ALT_BASEEntity = entity as PersistentPM_ALT_BASE;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlInsert);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, PM_ALT_BASEEntity.AlertID);
                db.AddInParameter(dbCommand, "@AlertName", DbType.String, PM_ALT_BASEEntity.AlertName);
                db.AddInParameter(dbCommand, "@AlertAlias", DbType.String, PM_ALT_BASEEntity.AlertAlias);
                db.AddInParameter(dbCommand, "@SqlScript", DbType.String, PM_ALT_BASEEntity.SqlScript);
                db.AddInParameter(dbCommand, "@URL", DbType.String, PM_ALT_BASEEntity.URL);
                db.AddInParameter(dbCommand, "@AlertDesc", DbType.String, PM_ALT_BASEEntity.AlertDesc);
                db.AddInParameter(dbCommand, "@AlertContent", DbType.String, PM_ALT_BASEEntity.AlertContent);
                db.AddInParameter(dbCommand, "@Category", DbType.String, PM_ALT_BASEEntity.Category);
                db.AddInParameter(dbCommand, "@AlertType", DbType.Int32, PM_ALT_BASEEntity.AlertType);
                db.AddInParameter(dbCommand, "@Format", DbType.String, PM_ALT_BASEEntity.Format);
                db.AddInParameter(dbCommand, "@AlertObject", DbType.String, PM_ALT_BASEEntity.AlertObject);
                db.AddInParameter(dbCommand, "@PreProcedure", DbType.String, PM_ALT_BASEEntity.PreProcedure);
                db.AddInParameter(dbCommand, "@PostProcedure", DbType.String, PM_ALT_BASEEntity.PostProcedure);
                db.AddInParameter(dbCommand, "@AlertInterval", DbType.Int32, PM_ALT_BASEEntity.AlertInterval);
                db.AddInParameter(dbCommand, "@AlertTimePoints", DbType.String, PM_ALT_BASEEntity.AlertTimePoints);
                db.AddInParameter(dbCommand, "@LastAlertedTime", DbType.DateTime, PM_ALT_BASEEntity.LastAlertedTime);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, PM_ALT_BASEEntity.IsActive);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_BASEEntity.RowDeleted);
                db.AddInParameter(dbCommand, "@CreatedBy", DbType.String, PM_ALT_BASEEntity.CreatedBy);
                db.AddInParameter(dbCommand, "@CreatedOn", DbType.DateTime, PM_ALT_BASEEntity.CreatedOn);
                db.AddInParameter(dbCommand, "@ModifiedBy", DbType.String, PM_ALT_BASEEntity.ModifiedBy);
                db.AddInParameter(dbCommand, "@ModifiedOn", DbType.DateTime, PM_ALT_BASEEntity.ModifiedOn);

                int result = db.ExecuteNonQuery(dbCommand, transaction);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_BASEEntity as PM_ALT_BASE;
        }

        #endregion Insert

        #region Delete
        /// <summary>
        /// Delete 
        /// </summary>  
        public void Delete(object entityId)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlDelete);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, entityId);
                int result = db.ExecuteNonQuery(dbCommand);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }


        /// <summary>
        /// Delete with transaction
        /// </summary>  
        public void Delete(object entityId, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlDelete);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, entityId);
                int result = db.ExecuteNonQuery(dbCommand, transaction);
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        #endregion Delete

        #region Get
        /// <summary>
        /// Get
        /// </summary>
        public PM_ALT_BASE Get(object entityId)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");

            PM_ALT_BASE PM_ALT_BASEEntity = null;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlGet);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, entityId);
                using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                {
                    if (dataReader.Read())
                    {
                        PM_ALT_BASEEntity = ReadEntity(dataReader);
                    }
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_BASEEntity;
        }


        /// <summary>
        /// Get with transaction
        /// </summary>
        public PM_ALT_BASE Get(object entityId, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entityId, "entityId");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PM_ALT_BASE PM_ALT_BASEEntity = null;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlGet);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, entityId);
                using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                {
                    if (dataReader.Read())
                    {
                        PM_ALT_BASEEntity = ReadEntity(dataReader);
                    }
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_BASEEntity;
        }

        #endregion Get

        #region Update

        /// <summary>
        /// Update
        /// </summary>

        public void Update(PM_ALT_BASE entity)
        {
            Update(entity, true);
        }

        public void Update(PM_ALT_BASE entity, bool updateAll)
        {
            if (!updateAll)
            {
                UpdateSome(entity);
            }
            else
            {
                UpdateAll(entity);
            }
        }

        private void UpdateAll(PM_ALT_BASE entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");

            PersistentPM_ALT_BASE PM_ALT_BASEEntity = entity as PersistentPM_ALT_BASE;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlUpdate);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, PM_ALT_BASEEntity.AlertID);
                db.AddInParameter(dbCommand, "@AlertName", DbType.String, PM_ALT_BASEEntity.AlertName);
                db.AddInParameter(dbCommand, "@AlertAlias", DbType.String, PM_ALT_BASEEntity.AlertAlias);
                db.AddInParameter(dbCommand, "@SqlScript", DbType.String, PM_ALT_BASEEntity.SqlScript);
                db.AddInParameter(dbCommand, "@URL", DbType.String, PM_ALT_BASEEntity.URL);
                db.AddInParameter(dbCommand, "@AlertDesc", DbType.String, PM_ALT_BASEEntity.AlertDesc);
                db.AddInParameter(dbCommand, "@AlertContent", DbType.String, PM_ALT_BASEEntity.AlertContent);
                db.AddInParameter(dbCommand, "@Category", DbType.String, PM_ALT_BASEEntity.Category);
                db.AddInParameter(dbCommand, "@AlertType", DbType.Int32, PM_ALT_BASEEntity.AlertType);
                db.AddInParameter(dbCommand, "@Format", DbType.String, PM_ALT_BASEEntity.Format);
                db.AddInParameter(dbCommand, "@AlertObject", DbType.String, PM_ALT_BASEEntity.AlertObject);
                db.AddInParameter(dbCommand, "@PreProcedure", DbType.String, PM_ALT_BASEEntity.PreProcedure);
                db.AddInParameter(dbCommand, "@PostProcedure", DbType.String, PM_ALT_BASEEntity.PostProcedure);
                db.AddInParameter(dbCommand, "@AlertInterval", DbType.Int32, PM_ALT_BASEEntity.AlertInterval);
                db.AddInParameter(dbCommand, "@AlertTimePoints", DbType.String, PM_ALT_BASEEntity.AlertTimePoints);
                db.AddInParameter(dbCommand, "@LastAlertedTime", DbType.DateTime, PM_ALT_BASEEntity.LastAlertedTime);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, PM_ALT_BASEEntity.IsActive);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_BASEEntity.RowDeleted);
                db.AddInParameter(dbCommand, "@CreatedBy", DbType.String, PM_ALT_BASEEntity.CreatedBy);
                db.AddInParameter(dbCommand, "@CreatedOn", DbType.DateTime, PM_ALT_BASEEntity.CreatedOn);
                db.AddInParameter(dbCommand, "@ModifiedBy", DbType.String, PM_ALT_BASEEntity.ModifiedBy);
                db.AddInParameter(dbCommand, "@ModifiedOn", DbType.DateTime, PM_ALT_BASEEntity.ModifiedOn);
                int result = db.ExecuteNonQuery(dbCommand);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        private void UpdateSome(PM_ALT_BASE entity)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");

            PersistentPM_ALT_BASE PM_ALT_BASEEntity = entity as PersistentPM_ALT_BASE;

            StringBuilder sqlUpdateSome = new StringBuilder();
            sqlUpdateSome.Append("UPDATE dbo.PM_ALT_BASE SET ");

            PropertyInfo[] propertyInfos = PM_ALT_BASEEntity.GetType().GetProperties();
            Hashtable propertyValues = new System.Collections.Hashtable();
            int columnCountForUpdate = 0;

            foreach (PropertyInfo propertyInfo in propertyInfos)
            {
                if (EntityMapping.ContainsProperty(propertyInfo.Name))
                {
                    object propertyValue = propertyInfo.GetValue(PM_ALT_BASEEntity, null);
                    ORProperty property = EntityMapping[propertyInfo.Name];
                    if (!property.IsPrimaryKey)
                    {
                        if (!PM_ALT_BASEEntity.IsDefaultValue(propertyInfo.Name))
                        {
                            propertyValues[propertyInfo.Name] = propertyValue;

                            sqlUpdateSome.Append(" " + property.ColumnName + " = @" + property.ColumnName + ",");
                            columnCountForUpdate++;
                        }
                    }
                    else
                    {
                        propertyValues[propertyInfo.Name] = propertyValue;
                    }
                }
            }
            if (columnCountForUpdate == 0)
            {
                return;
            }

            sqlUpdateSome.Remove(sqlUpdateSome.Length - 1, 1);
            sqlUpdateSome.Append(" WHERE 1 = 1 ");
            sqlUpdateSome.Append(" AND AlertID = @AlertID ");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(sqlUpdateSome.ToString());

                foreach (DictionaryEntry de in propertyValues)
                {
                    ORProperty property = EntityMapping[de.Key.ToString()];
                    db.AddInParameter(dbCommand, "@" + property.ColumnName, property.DatabaseType, de.Value);
                }

                int result = db.ExecuteNonQuery(dbCommand);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        /// <summary>
        /// Update with transaction
        /// </summary>

        public void Update(PM_ALT_BASE entity, DbTransaction transaction)
        {
            Update(entity, true, transaction);
        }

        public void Update(PM_ALT_BASE entity, bool updateAll, DbTransaction transaction)
        {
            if (!updateAll)
            {
                UpdateSome(entity, transaction);
            }
            else
            {
                UpdateAll(entity, transaction);
            }
        }

        private void UpdateAll(PM_ALT_BASE entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PersistentPM_ALT_BASE PM_ALT_BASEEntity = entity as PersistentPM_ALT_BASE;

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(PM_ALT_BASEDAO.SqlUpdate);

                db.AddInParameter(dbCommand, "@AlertID", DbType.Guid, PM_ALT_BASEEntity.AlertID);
                db.AddInParameter(dbCommand, "@AlertName", DbType.String, PM_ALT_BASEEntity.AlertName);
                db.AddInParameter(dbCommand, "@AlertAlias", DbType.String, PM_ALT_BASEEntity.AlertAlias);
                db.AddInParameter(dbCommand, "@SqlScript", DbType.String, PM_ALT_BASEEntity.SqlScript);
                db.AddInParameter(dbCommand, "@URL", DbType.String, PM_ALT_BASEEntity.URL);
                db.AddInParameter(dbCommand, "@AlertDesc", DbType.String, PM_ALT_BASEEntity.AlertDesc);
                db.AddInParameter(dbCommand, "@AlertContent", DbType.String, PM_ALT_BASEEntity.AlertContent);
                db.AddInParameter(dbCommand, "@Category", DbType.String, PM_ALT_BASEEntity.Category);
                db.AddInParameter(dbCommand, "@AlertType", DbType.Int32, PM_ALT_BASEEntity.AlertType);
                db.AddInParameter(dbCommand, "@Format", DbType.String, PM_ALT_BASEEntity.Format);
                db.AddInParameter(dbCommand, "@AlertObject", DbType.String, PM_ALT_BASEEntity.AlertObject);
                db.AddInParameter(dbCommand, "@PreProcedure", DbType.String, PM_ALT_BASEEntity.PreProcedure);
                db.AddInParameter(dbCommand, "@PostProcedure", DbType.String, PM_ALT_BASEEntity.PostProcedure);
                db.AddInParameter(dbCommand, "@AlertInterval", DbType.Int32, PM_ALT_BASEEntity.AlertInterval);
                db.AddInParameter(dbCommand, "@AlertTimePoints", DbType.String, PM_ALT_BASEEntity.AlertTimePoints);
                db.AddInParameter(dbCommand, "@LastAlertedTime", DbType.DateTime, PM_ALT_BASEEntity.LastAlertedTime);
                db.AddInParameter(dbCommand, "@IsActive", DbType.Boolean, PM_ALT_BASEEntity.IsActive);
                db.AddInParameter(dbCommand, "@RowDeleted", DbType.Boolean, PM_ALT_BASEEntity.RowDeleted);
                db.AddInParameter(dbCommand, "@CreatedBy", DbType.String, PM_ALT_BASEEntity.CreatedBy);
                db.AddInParameter(dbCommand, "@CreatedOn", DbType.DateTime, PM_ALT_BASEEntity.CreatedOn);
                db.AddInParameter(dbCommand, "@ModifiedBy", DbType.String, PM_ALT_BASEEntity.ModifiedBy);
                db.AddInParameter(dbCommand, "@ModifiedOn", DbType.DateTime, PM_ALT_BASEEntity.ModifiedOn);
                int result = db.ExecuteNonQuery(dbCommand, transaction);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        private void UpdateSome(PM_ALT_BASE entity, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(entity, "entity");
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            PersistentPM_ALT_BASE PM_ALT_BASEEntity = entity as PersistentPM_ALT_BASE;

            StringBuilder sqlUpdateSome = new StringBuilder();
            sqlUpdateSome.Append("UPDATE dbo.PM_ALT_BASE SET ");

            PropertyInfo[] propertyInfos = PM_ALT_BASEEntity.GetType().GetProperties();
            Hashtable propertyValues = new System.Collections.Hashtable();
            int columnCountForUpdate = 0;

            foreach (PropertyInfo propertyInfo in propertyInfos)
            {
                if (EntityMapping.ContainsProperty(propertyInfo.Name))
                {
                    object propertyValue = propertyInfo.GetValue(PM_ALT_BASEEntity, null);
                    ORProperty property = EntityMapping[propertyInfo.Name];
                    if (!property.IsPrimaryKey)
                    {
                        if (!PM_ALT_BASEEntity.IsDefaultValue(propertyInfo.Name))
                        {
                            propertyValues[propertyInfo.Name] = propertyValue;

                            sqlUpdateSome.Append(" " + property.ColumnName + " = @" + property.ColumnName + ",");
                            columnCountForUpdate++;
                        }
                    }
                    else
                    {
                        propertyValues[propertyInfo.Name] = propertyValue;
                    }
                }
            }
            if (columnCountForUpdate == 0)
            {
                return;
            }

            sqlUpdateSome.Remove(sqlUpdateSome.Length - 1, 1);
            sqlUpdateSome.Append(" WHERE 1 = 1 ");
            sqlUpdateSome.Append(" AND AlertID = @AlertID ");

            try
            {
                Database db = GetDatabaseInstance();
                DbCommand dbCommand = db.GetSqlStringCommand(sqlUpdateSome.ToString());

                foreach (DictionaryEntry de in propertyValues)
                {
                    ORProperty property = EntityMapping[de.Key.ToString()];
                    db.AddInParameter(dbCommand, "@" + property.ColumnName, property.DatabaseType, de.Value);
                }

                int result = db.ExecuteNonQuery(dbCommand, transaction);

                if (result == 0)
                {
                    throw new EntityNotFoundException();
                }
            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }
        }

        /// <summary>
        /// ORMapping
        /// </summary>

        private OREntity entityMapping;

        public OREntity EntityMapping
        {
            get
            {
                if (entityMapping == null)
                {
                    LoadMappings();
                }

                return entityMapping;
            }
        }

        private void LoadMappings()
        {
            entityMapping = new OREntity();
            entityMapping.Name = "PM_ALT_BASE";
            entityMapping.TableName = "dbo.PM_ALT_BASE";

            foreach (object[] propertyMapping in this.PropertyMappings)
            {
                ORProperty property = new ORProperty();

                property.ColumnName = (string)propertyMapping[0];
                property.DatabaseType = (DbType)propertyMapping[1];
                property.IsNullable = (bool)propertyMapping[2];
                property.IsPrimaryKey = (bool)propertyMapping[3];
                property.Name = (string)propertyMapping[4];
                property.Type = (Type)propertyMapping[5];

                entityMapping.Properties.Add(property);
            }
        }

        private object[][] PropertyMappings = new object[][] 
        {
            new object[] {"AlertID", DbType.Guid, false, true, "AlertID",typeof(Guid?)},
            new object[] {"AlertName", DbType.String, false, false, "AlertName",typeof(String)},
            new object[] {"AlertAlias", DbType.String, false, false, "AlertAlias",typeof(String)},
            new object[] {"SqlScript", DbType.String, true, false, "SqlScript",typeof(String)},
            new object[] {"URL", DbType.String, true, false, "URL",typeof(String)},
            new object[] {"AlertDesc", DbType.String, true, false, "AlertDesc",typeof(String)},
            new object[] {"AlertContent", DbType.String, true, false, "AlertContent",typeof(String)},
            new object[] {"Category", DbType.String, true, false, "Category",typeof(String)},
            new object[] {"AlertType", DbType.Int32, true, false, "AlertType",typeof(Int32?)},
            new object[] {"Format", DbType.String, true, false, "Format",typeof(String)},
            new object[] {"AlertObject", DbType.String, true, false, "AlertObject",typeof(String)},
            new object[] {"PreProcedure", DbType.String, true, false, "PreProcedure",typeof(String)},
            new object[] {"PostProcedure", DbType.String, true, false, "PostProcedure",typeof(String)},
            new object[] {"AlertInterval", DbType.Int32, true, false, "AlertInterval",typeof(Int32?)},
            new object[] {"AlertTimePoints", DbType.String, true, false, "AlertTimePoints",typeof(String)},
            new object[] {"LastAlertedTime", DbType.DateTime, true, false, "LastAlertedTime",typeof(DateTime?)},
            new object[] {"IsActive", DbType.Boolean, false, false, "IsActive",typeof(Boolean?)},
            new object[] {"RowDeleted", DbType.Boolean, false, false, "RowDeleted",typeof(Boolean?)},
            new object[] {"CreatedBy", DbType.String, true, false, "CreatedBy",typeof(String)},
            new object[] {"CreatedOn", DbType.DateTime, false, false, "CreatedOn",typeof(DateTime?)},
            new object[] {"ModifiedBy", DbType.String, true, false, "ModifiedBy",typeof(String)},
            new object[] {"ModifiedOn", DbType.DateTime, true, false, "ModifiedOn",typeof(DateTime?)},
        };


        #endregion Update

        #region Find
        /// <summary>
        /// Find
        /// </summary>
        public IList<PM_ALT_BASE> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords)
        {
            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<PM_ALT_BASE> PM_ALT_BASEList = new List<PM_ALT_BASE>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY AlertID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, PM_ALT_BASEDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       PM_ALT_BASEDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand))
                    {
                        while (dataReader.Read())
                        {
                            PM_ALT_BASEList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                //DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                //totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_BASEList;
        }

        /// <summary>
        /// Find with transaction
        /// </summary>
        public IList<PM_ALT_BASE> Find(int pageIndex, int pageSize, IFilter filter, ISort sort, out long totalRecords, DbTransaction transaction)
        {
            ArgumentValidator.CheckForNullArgument(transaction, "transaction");

            if (pageIndex < 0)
            {
                throw new ArgumentOutOfRangeException("pageIndex");
            }

            if (pageSize < -1)
            {
                throw new ArgumentOutOfRangeException("pageSize");
            }

            IList<PM_ALT_BASE> PM_ALT_BASEList = new List<PM_ALT_BASE>();
            totalRecords = 0;

            string cmdText;
            string cmdCountText;

            int beginIndex = pageSize * pageIndex;

            string filterClause = "";
            if (filter == null || String.IsNullOrEmpty(filter.ToQueryString()))
            {
            }
            else
            {
                filterClause = filter.ToQueryString();
            }

            string sortClause = "";
            if (sort == null || String.IsNullOrEmpty(sort.ToSortString()))
            {
                sortClause = "ORDER BY AlertID";
            }
            else
            {
                sortClause = sort.ToSortString();
            }

            cmdCountText = string.Format(CultureInfo.InvariantCulture, SqlCount, filterClause);

            if (pageSize == -1)
            {
                cmdText = string.Format(
                CultureInfo.InvariantCulture, PM_ALT_BASEDAO.SqlSelectAll, filterClause, sortClause);
            }
            else
            {
                cmdText = String.Format(
                       CultureInfo.InvariantCulture,
                       PM_ALT_BASEDAO.SqlSelect, pageSize.ToString(), filterClause, beginIndex.ToString(), filterClause, sortClause, sortClause);
            }

            try
            {
                Database db = GetDatabaseInstance();

                if (pageSize != 0)
                {
                    DbCommand dbCommand = db.GetSqlStringCommand(cmdText);
                    using (IDataReader dataReader = db.ExecuteReader(dbCommand, transaction))
                    {
                        while (dataReader.Read())
                        {
                            PM_ALT_BASEList.Add(ReadEntity(dataReader));
                        }
                    }
                }

                DbCommand dbCommandCount = db.GetSqlStringCommand(cmdCountText);
                totalRecords = Convert.ToInt64(db.ExecuteScalar(dbCommandCount, transaction));

            }
            catch (Exception ex)
            {
                ExceptionPolicy.HandleException(ex, ExceptionPolicy.DataAccessDefaultPolicy);
            }

            return PM_ALT_BASEList;
        }

        #endregion Find

        #endregion IDataAccessor members


        #region Private Method

        private static Database GetDatabaseInstance()
        {
            return DatabaseFactory.CreateDatabase(DatabaseEnum.SITBusinessDB);
        }

        private static PM_ALT_BASE ReadEntity(IDataReader dataReader)
        {
            PM_ALT_BASE PM_ALT_BASEEntity = new PM_ALT_BASE();
            object value;


            value = dataReader["AlertID"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertID = (Guid?)value;
            }

            value = dataReader["AlertName"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertName = (String)value;
            }

            value = dataReader["AlertAlias"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertAlias = (String)value;
            }

            value = dataReader["SqlScript"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.SqlScript = (String)value;
            }

            value = dataReader["URL"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.URL = (String)value;
            }

            value = dataReader["AlertDesc"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertDesc = (String)value;
            }

            value = dataReader["AlertContent"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertContent = (String)value;
            }

            value = dataReader["Category"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.Category = (String)value;
            }

            value = dataReader["AlertType"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertType = (Int32?)value;
            }

            value = dataReader["Format"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.Format = (String)value;
            }

            value = dataReader["AlertObject"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertObject = (String)value;
            }

            value = dataReader["PreProcedure"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.PreProcedure = (String)value;
            }

            value = dataReader["PostProcedure"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.PostProcedure = (String)value;
            }

            value = dataReader["AlertInterval"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertInterval = (Int32?)value;
            }

            value = dataReader["AlertTimePoints"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.AlertTimePoints = (String)value;
            }

            value = dataReader["LastAlertedTime"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.LastAlertedTime = (DateTime?)value;
            }

            value = dataReader["IsActive"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.IsActive = (Boolean?)value;
            }

            value = dataReader["RowDeleted"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.RowDeleted = (Boolean?)value;
            }

            value = dataReader["CreatedBy"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.CreatedBy = (String)value;
            }

            value = dataReader["CreatedOn"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.CreatedOn = (DateTime?)value;
            }

            value = dataReader["ModifiedBy"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.ModifiedBy = (String)value;
            }

            value = dataReader["ModifiedOn"];
            if (value != DBNull.Value)
            {
                PM_ALT_BASEEntity.ModifiedOn = (DateTime?)value;
            }

            return PM_ALT_BASEEntity;
        }

        #endregion Private Method

    }
}
