
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// LiXiao Info Tech Ltd. Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections.Generic;
using System.Text;
using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.Common
{
    /// <summary>
    /// CV_PM_ALT_CRITERION Class.
    /// </summary>
    /// Title: CV_PM_ALT_CRITERION
    /// Copyright: LiXiao Info Tech Ltd.
    /// Version: 1.0
    [Serializable]
    public class CV_PM_ALT_CRITERION : PersistentCV_PM_ALT_CRITERION
    {
    }
}

namespace Siemens.Simatic.ALT.Common.Persistence
{
    /// <summary>
    /// CV_PM_ALT_CRITERION PersistentClass.
    /// </summary>
    /// Title: PersistentCV_PM_ALT_CRITERION
    /// Copyright: LiXiao Info Tech Ltd.
    /// Version: 1.0
    [Serializable]
    public class PersistentCV_PM_ALT_CRITERION : BaseEntity
    {
        public PersistentCV_PM_ALT_CRITERION()
            : base()
        {
            this.InitialDefaultValues();
        }


        #region Private Fields

        private Guid? _CriterionID;
        private Guid? _AlertID;
        private String _AlertName;
        private String _AlertAlias;
        private String _Relation;
        private String _Element;
        private String _ColumnAlias;
        private String _Alias;
        private String _Operator;
        private String _Value;
        private Int32? _ScaleType;
        private String _ScaleTypeName;
        private Int32? _Action;
        private String _ActionName;
        private Int32? _Sequence;
        private Guid? _ParentID;
        private Int32? _CritLevel;
        private Boolean? _IsActive;
        private String _CreatedBy;
        private DateTime? _CreatedOn;
        private String _ModifiedBy;
        private DateTime? _ModifiedOn;

        #endregion

        #region Public Properties

        public Guid? CriterionID
        {
            get { return _CriterionID; }
            set
            {
                _CriterionID = value;
                this.SetNotDefaultValue("CriterionID");
            }
        }
        public Guid? AlertID
        {
            get { return _AlertID; }
            set
            {
                _AlertID = value;
                this.SetNotDefaultValue("AlertID");
            }
        }
        public String AlertName
        {
            get { return _AlertName; }
            set
            {
                _AlertName = value;
                this.SetNotDefaultValue("AlertName");
            }
        }
        public String AlertAlias
        {
            get { return _AlertAlias; }
            set
            {
                _AlertAlias = value;
                this.SetNotDefaultValue("AlertAlias");
            }
        }
        public String Relation
        {
            get { return _Relation; }
            set
            {
                _Relation = value;
                this.SetNotDefaultValue("Relation");
            }
        }
        public String Element
        {
            get { return _Element; }
            set
            {
                _Element = value;
                this.SetNotDefaultValue("Element");
            }
        }
        public String ColumnAlias
        {
            get { return _ColumnAlias; }
            set
            {
                _ColumnAlias = value;
                this.SetNotDefaultValue("ColumnAlias");
            }
        }
        public String Alias
        {
            get { return _Alias; }
            set
            {
                _Alias = value;
                this.SetNotDefaultValue("Alias");
            }
        }
        public String Operator
        {
            get { return _Operator; }
            set
            {
                _Operator = value;
                this.SetNotDefaultValue("Operator");
            }
        }
        public String Value
        {
            get { return _Value; }
            set
            {
                _Value = value;
                this.SetNotDefaultValue("Value");
            }
        }
        public Int32? ScaleType
        {
            get { return _ScaleType; }
            set
            {
                _ScaleType = value;
                this.SetNotDefaultValue("ScaleType");
            }
        }
        public String ScaleTypeName
        {
            get { return _ScaleTypeName; }
            set
            {
                _ScaleTypeName = value;
                this.SetNotDefaultValue("ScaleTypeName");
            }
        }
        public Int32? Action
        {
            get { return _Action; }
            set
            {
                _Action = value;
                this.SetNotDefaultValue("Action");
            }
        }
        public String ActionName
        {
            get { return _ActionName; }
            set
            {
                _ActionName = value;
                this.SetNotDefaultValue("ActionName");
            }
        }
        public Int32? Sequence
        {
            get { return _Sequence; }
            set
            {
                _Sequence = value;
                this.SetNotDefaultValue("Sequence");
            }
        }
        public Guid? ParentID
        {
            get { return _ParentID; }
            set
            {
                _ParentID = value;
                this.SetNotDefaultValue("ParentID");
            }
        }
        public Int32? CritLevel
        {
            get { return _CritLevel; }
            set
            {
                _CritLevel = value;
                this.SetNotDefaultValue("CritLevel");
            }
        }
        public Boolean? IsActive
        {
            get { return _IsActive; }
            set
            {
                _IsActive = value;
                this.SetNotDefaultValue("IsActive");
            }
        }
        public String CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                this.SetNotDefaultValue("CreatedBy");
            }
        }
        public DateTime? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                this.SetNotDefaultValue("CreatedOn");
            }
        }
        public String ModifiedBy
        {
            get { return _ModifiedBy; }
            set
            {
                _ModifiedBy = value;
                this.SetNotDefaultValue("ModifiedBy");
            }
        }
        public DateTime? ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                this.SetNotDefaultValue("ModifiedOn");
            }
        }

        #endregion

    }
}
