
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections.Generic;
using System.Text;
using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.Common
{
    /// <summary>
    /// CV_PM_WECHAT_AGENT Class.
    /// </summary>
    /// Title: CV_PM_WECHAT_AGENT
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class CV_PM_WECHAT_AGENT : PersistentCV_PM_WECHAT_AGENT
    {
    }
}

namespace Siemens.Simatic.ALT.Common.Persistence
{
    /// <summary>
    /// CV_PM_WECHAT_AGENT PersistentClass.
    /// </summary>
    /// Title: PersistentCV_PM_WECHAT_AGENT
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PersistentCV_PM_WECHAT_AGENT : BaseEntity
    {
        public PersistentCV_PM_WECHAT_AGENT()
            : base()
        {
            this.InitialDefaultValues();
        }


        #region Private Fields

        private Guid? _AgentGuid;
        private Int32? _AgentID;
        private String _Name;
        private String _Square_logo_url;
        private String _SecretID;
        private String _CreatedBy;
        private DateTime? _CreatedOn;
        private String _UpdatedBy;
        private DateTime? _UpdatedOn;

        #endregion

        #region Public Properties

        public Guid? AgentGuid
        {
            get { return _AgentGuid; }
            set
            {
                _AgentGuid = value;
                this.SetNotDefaultValue("AgentGuid");
            }
        }
        public Int32? AgentID
        {
            get { return _AgentID; }
            set
            {
                _AgentID = value;
                this.SetNotDefaultValue("AgentID");
            }
        }
        public String Name
        {
            get { return _Name; }
            set
            {
                _Name = value;
                this.SetNotDefaultValue("Name");
            }
        }
        public String Square_logo_url
        {
            get { return _Square_logo_url; }
            set
            {
                _Square_logo_url = value;
                this.SetNotDefaultValue("Square_logo_url");
            }
        }
        public String SecretID
        {
            get { return _SecretID; }
            set
            {
                _SecretID = value;
                this.SetNotDefaultValue("SecretID");
            }
        }
        public String CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                this.SetNotDefaultValue("CreatedBy");
            }
        }
        public DateTime? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                this.SetNotDefaultValue("CreatedOn");
            }
        }
        public String UpdatedBy
        {
            get { return _UpdatedBy; }
            set
            {
                _UpdatedBy = value;
                this.SetNotDefaultValue("UpdatedBy");
            }
        }
        public DateTime? UpdatedOn
        {
            get { return _UpdatedOn; }
            set
            {
                _UpdatedOn = value;
                this.SetNotDefaultValue("UpdatedOn");
            }
        }

        #endregion

    }
}
