
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections.Generic;
using System.Text;
using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.Common
{
    /// <summary>
    /// PM_ALT_BASE Class.
    /// </summary>
    /// Title: PM_ALT_BASE
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PM_ALT_BASE : PersistentPM_ALT_BASE
    {
    }
}

namespace Siemens.Simatic.ALT.Common.Persistence
{
    /// <summary>
    /// PM_ALT_BASE PersistentClass.
    /// </summary>
    /// Title: PersistentPM_ALT_BASE
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PersistentPM_ALT_BASE : BaseEntity
    {
        public PersistentPM_ALT_BASE() : base()
        {
            this.InitialDefaultValues();
        }


        #region Private Fields

        private Guid? _AlertID;
        private String _AlertName;
        private String _AlertAlias;
        private String _SqlScript;
        private String _URL;
        private String _AlertDesc;
        private String _AlertContent;
        private String _Category;
        private Int32? _AlertType;
        private String _Format;
        private String _AlertObject;
        private String _PreProcedure;
        private String _PostProcedure;
        private Int32? _AlertInterval;
        private String _AlertTimePoints;
        private DateTime? _LastAlertedTime;
        private Boolean? _IsActive;
        private Boolean? _RowDeleted;
        private String _CreatedBy;
        private DateTime? _CreatedOn;
        private String _ModifiedBy;
        private DateTime? _ModifiedOn;

        #endregion

        #region Public Properties

        public Guid? AlertID
        {
            get { return _AlertID; }
            set
            {
                _AlertID = value;
                this.SetNotDefaultValue("AlertID");
            }
        }
        public String AlertName
        {
            get { return _AlertName; }
            set
            {
                _AlertName = value;
                this.SetNotDefaultValue("AlertName");
            }
        }
        public String AlertAlias
        {
            get { return _AlertAlias; }
            set
            {
                _AlertAlias = value;
                this.SetNotDefaultValue("AlertAlias");
            }
        }
        public String SqlScript
        {
            get { return _SqlScript; }
            set
            {
                _SqlScript = value;
                this.SetNotDefaultValue("SqlScript");
            }
        }
        public String URL
        {
            get { return _URL; }
            set
            {
                _URL = value;
                this.SetNotDefaultValue("URL");
            }
        }
        public String AlertDesc
        {
            get { return _AlertDesc; }
            set
            {
                _AlertDesc = value;
                this.SetNotDefaultValue("AlertDesc");
            }
        }
        public String AlertContent
        {
            get { return _AlertContent; }
            set
            {
                _AlertContent = value;
                this.SetNotDefaultValue("AlertContent");
            }
        }
        public String Category
        {
            get { return _Category; }
            set
            {
                _Category = value;
                this.SetNotDefaultValue("Category");
            }
        }
        public Int32? AlertType
        {
            get { return _AlertType; }
            set
            {
                _AlertType = value;
                this.SetNotDefaultValue("AlertType");
            }
        }
        public String Format
        {
            get { return _Format; }
            set
            {
                _Format = value;
                this.SetNotDefaultValue("Format");
            }
        }
        public String AlertObject
        {
            get { return _AlertObject; }
            set
            {
                _AlertObject = value;
                this.SetNotDefaultValue("AlertObject");
            }
        }
        public String PreProcedure
        {
            get { return _PreProcedure; }
            set
            {
                _PreProcedure = value;
                this.SetNotDefaultValue("PreProcedure");
            }
        }
        public String PostProcedure
        {
            get { return _PostProcedure; }
            set
            {
                _PostProcedure = value;
                this.SetNotDefaultValue("PostProcedure");
            }
        }
        public Int32? AlertInterval
        {
            get { return _AlertInterval; }
            set
            {
                _AlertInterval = value;
                this.SetNotDefaultValue("AlertInterval");
            }
        }
        public String AlertTimePoints
        {
            get { return _AlertTimePoints; }
            set
            {
                _AlertTimePoints = value;
                this.SetNotDefaultValue("AlertTimePoints");
            }
        }
        public DateTime? LastAlertedTime
        {
            get { return _LastAlertedTime; }
            set
            {
                _LastAlertedTime = value;
                this.SetNotDefaultValue("LastAlertedTime");
            }
        }
        public Boolean? IsActive
        {
            get { return _IsActive; }
            set
            {
                _IsActive = value;
                this.SetNotDefaultValue("IsActive");
            }
        }
        public Boolean? RowDeleted
        {
            get { return _RowDeleted; }
            set
            {
                _RowDeleted = value;
                this.SetNotDefaultValue("RowDeleted");
            }
        }
        public String CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                this.SetNotDefaultValue("CreatedBy");
            }
        }
        public DateTime? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                this.SetNotDefaultValue("CreatedOn");
            }
        }
        public String ModifiedBy
        {
            get { return _ModifiedBy; }
            set
            {
                _ModifiedBy = value;
                this.SetNotDefaultValue("ModifiedBy");
            }
        }
        public DateTime? ModifiedOn
        {
            get { return _ModifiedOn; }
            set
            {
                _ModifiedOn = value;
                this.SetNotDefaultValue("ModifiedOn");
            }
        }

        #endregion

    }
}
