
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections.Generic;
using System.Text;
using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.Common
{
    /// <summary>
    /// PM_ALT_NOTI Class.
    /// </summary>
    /// Title: PM_ALT_NOTI
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PM_ALT_NOTI : PersistentPM_ALT_NOTI
    {
    }
}

namespace Siemens.Simatic.ALT.Common.Persistence
{
    /// <summary>
    /// PM_ALT_NOTI PersistentClass.
    /// </summary>
    /// Title: PersistentPM_ALT_NOTI
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PersistentPM_ALT_NOTI : BaseEntity
    {
        public PersistentPM_ALT_NOTI()
            : base()
        {
            this.InitialDefaultValues();
        }


        #region Private Fields

        private Guid? _NotiGuid;
        private Guid? _AlertID;
        private Guid? _UserGuid;
        private Guid? _DepartmentGuid;
        private Guid? _AgentGuid;
        private String _CreatedBy;
        private DateTime? _CreatedOn;
        private String _UpdatedBy;
        private DateTime? _UpdatedOn;

        #endregion

        #region Public Properties

        public Guid? NotiGuid
        {
            get { return _NotiGuid; }
            set
            {
                _NotiGuid = value;
                this.SetNotDefaultValue("NotiGuid");
            }
        }
        public Guid? AlertID
        {
            get { return _AlertID; }
            set
            {
                _AlertID = value;
                this.SetNotDefaultValue("AlertID");
            }
        }
        public Guid? UserGuid
        {
            get { return _UserGuid; }
            set
            {
                _UserGuid = value;
                this.SetNotDefaultValue("UserGuid");
            }
        }
        public Guid? DepartmentGuid
        {
            get { return _DepartmentGuid; }
            set
            {
                _DepartmentGuid = value;
                this.SetNotDefaultValue("DepartmentGuid");
            }
        }
        public Guid? AgentGuid
        {
            get { return _AgentGuid; }
            set
            {
                _AgentGuid = value;
                this.SetNotDefaultValue("AgentGuid");
            }
        }
        public String CreatedBy
        {
            get { return _CreatedBy; }
            set
            {
                _CreatedBy = value;
                this.SetNotDefaultValue("CreatedBy");
            }
        }
        public DateTime? CreatedOn
        {
            get { return _CreatedOn; }
            set
            {
                _CreatedOn = value;
                this.SetNotDefaultValue("CreatedOn");
            }
        }
        public String UpdatedBy
        {
            get { return _UpdatedBy; }
            set
            {
                _UpdatedBy = value;
                this.SetNotDefaultValue("UpdatedBy");
            }
        }
        public DateTime? UpdatedOn
        {
            get { return _UpdatedOn; }
            set
            {
                _UpdatedOn = value;
                this.SetNotDefaultValue("UpdatedOn");
            }
        }

        #endregion

    }
}
