
//=====================================================================
// This file was generated by Siemens.Simatic Platform
// 
// Siemens Copyright (c) 2014 All rights reserved. 
//=====================================================================

using System;
using System.Collections.Generic;
using System.Text;
using Siemens.Simatic.Platform.Core;
using Siemens.Simatic.ALT.Common.Persistence;

namespace Siemens.Simatic.ALT.Common
{
    /// <summary>
    /// PM_WECHAT_USER_TEMP Class.
    /// </summary>
    /// Title: PM_WECHAT_USER_TEMP
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PM_WECHAT_USER_TEMP : PersistentPM_WECHAT_USER_TEMP
    {
    }
}

namespace Siemens.Simatic.ALT.Common.Persistence
{
    /// <summary>
    /// PM_WECHAT_USER_TEMP PersistentClass.
    /// </summary>
    /// Title: PersistentPM_WECHAT_USER_TEMP
    /// Copyright: Siemens
    /// Version: 1.0
    [Serializable]
    public class PersistentPM_WECHAT_USER_TEMP : BaseEntity
    {
        public PersistentPM_WECHAT_USER_TEMP() : base()
        {
            this.InitialDefaultValues();
        }


        #region Private Fields

        private String _DepartID;
        private String _Userid;
        private String _Name;
        private String _English_name;
        private String _Mobile;
        private String _Position;
        private Int32? _Gender;
        private String _Email;
        private Boolean? _Isleader;
        private String _Avatar;
        private String _Telephone;

        #endregion

        #region Public Properties

        public String DepartID
        {
            get { return _DepartID; }
            set
            {
                _DepartID = value;
                this.SetNotDefaultValue("DepartID");
            }
        }
        public String Userid
        {
            get { return _Userid; }
            set
            {
                _Userid = value;
                this.SetNotDefaultValue("Userid");
            }
        }
        public String Name
        {
            get { return _Name; }
            set
            {
                _Name = value;
                this.SetNotDefaultValue("Name");
            }
        }
        public String English_name
        {
            get { return _English_name; }
            set
            {
                _English_name = value;
                this.SetNotDefaultValue("English_name");
            }
        }
        public String Mobile
        {
            get { return _Mobile; }
            set
            {
                _Mobile = value;
                this.SetNotDefaultValue("Mobile");
            }
        }
        public String Position
        {
            get { return _Position; }
            set
            {
                _Position = value;
                this.SetNotDefaultValue("Position");
            }
        }
        public Int32? Gender
        {
            get { return _Gender; }
            set
            {
                _Gender = value;
                this.SetNotDefaultValue("Gender");
            }
        }
        public String Email
        {
            get { return _Email; }
            set
            {
                _Email = value;
                this.SetNotDefaultValue("Email");
            }
        }
        public Boolean? Isleader
        {
            get { return _Isleader; }
            set
            {
                _Isleader = value;
                this.SetNotDefaultValue("Isleader");
            }
        }
        public String Avatar
        {
            get { return _Avatar; }
            set
            {
                _Avatar = value;
                this.SetNotDefaultValue("Avatar");
            }
        }
        public String Telephone
        {
            get { return _Telephone; }
            set
            {
                _Telephone = value;
                this.SetNotDefaultValue("Telephone");
            }
        }

        #endregion

    }
}
